# -*- coding: utf-8 -*-
"""
Builder for scripts/data/topup_part2_topics_2_to_32.py
Guarantees ALL topics from 2 to 32 reach 100+ unique authentic words!
"""
import sys
if sys.stdout.encoding != 'utf-8':
    try: sys.stdout.reconfigure(encoding='utf-8')
    except Exception: pass
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
sys.path.append(str(BASE_DIR / "scripts"))
sys.path.append(str(BASE_DIR / "scripts" / "data"))

from test_combine import base_map, all_supps

def get_current_seen(topic_name):
    seen = set()
    if topic_name in base_map:
        for w in base_map[topic_name]:
            seen.add(w["word"].strip().lower())
    for t, words in all_supps.items():
        if t == topic_name:
            for w in words:
                w_val = w["word"] if isinstance(w, dict) else w[0]
                seen.add(w_val.strip().lower())
    return seen

EXTRA_WORDS = {
    "Food, Cooking & Dining": [
        ("julienne", "/ˌdʒuːliˈɛn/", "v", "thái sợi mỏng dạng que diêm", "to cut food, especially vegetables, into long thin strips like matchsticks", "Julienne the fresh carrots and bell peppers for the gourmet salad.", "Thái sợi mỏng cà rốt và ớt chuông tươi cho món salad cao cấp.", ["shred", "cut into strips"], ["julienne carrots", "finely julienne"], "Julienne matchstick cut"),
        ("chiffonade", "/ˌʃɪfəˈnɑːd/", "n", "kỹ thuật thái dải ruy băng mỏng (lá thơm)", "a preparation of shredded or finely cut leaf vegetables used as a garnish", "Sprinkle a fragrant chiffonade of fresh basil over the pasta.", "Rắc một lớp lá húng quế thái sợi ruy băng thơm lừng lên đĩa mì Ý.", ["shredded herbs"], ["basil chiffonade", "mint chiffonade"], "Chiffon ribbon-thin herb cuts"),
    ],
    "Travel, Tourism & Transportation": [
        ("globetrotter", "/ˈɡloʊbˌtrɒtər/", "n", "người đi du lịch khắp năm châu bốn biển", "a person who travels regularly and frequently throughout the international world", "The seasoned globetrotter documented indigenous tribes across five continents.", "Người du lịch khắp năm châu dày dạn kinh nghiệm đã ghi lại tư liệu về các bộ lạc bản địa qua năm châu lục.", ["world traveler", "jet-setter"], ["avid globetrotter", "adventurous globetrotter"], "Trotting across the globe"),
        ("wayfinding", "/ˈweɪˌfaɪndɪŋ/", "n", "nghệ thuật định hướng tìm đường trong không gian", "the process or activity of ascertaining one's position and planning and following a route", "Modern airports employ intuitive architectural wayfinding signs to guide passenger flows.", "Các sân bay hiện đại sử dụng biển chỉ dẫn không gian trực quan để điều hướng dòng hành khách.", ["navigation", "orientation"], ["airport wayfinding", "wayfinding system"], "Finding the way through space"),
        ("itinerant", "/aɪˈtɪnərənt/", "adj", "nay đây mai đó, lưu động", "traveling from place to place, especially in search of work or trade", "Itinerant craftspeople set up open-air workshops at seasonal country fairs.", "Những người thợ thủ công lưu động đã mở các xưởng thủ công ngoài trời tại các hội chợ làng quê theo mùa.", ["nomadic", "peripatetic", "wandering"], ["itinerant worker", "itinerant musician"], "Iter (journey) roving traveler"),
    ],
    "Education & Academic Life": [
        ("valedictorian", "/ˌvælɪdɪkˈtɔːriən/", "n", "thủ khoa tốt nghiệp đại diện đọc diễn văn", "the student having the highest academic rank in a graduating class who delivers the farewell address", "The valedictorian inspired her peers with an impassioned graduation commencement speech.", "Nữ thủ khoa tốt nghiệp đã truyền cảm hứng cho các bạn đồng khóa bằng một bài diễn văn tốt nghiệp đầy nhiệt huyết.", ["top graduate", "honor student"], ["class valedictorian", "named valedictorian"], "Vale (farewell) + dicere (speak)"),
        ("salutatorian", "/səˌluːtəˈtɔːriən/", "n", "á khoa tốt nghiệp đại diện đọc diễn văn chào mừng", "the student ranking second highest in a graduating class who delivers the opening address", "The salutatorian welcomed faculty, alumni, and parents to the university auditorium.", "Vị á khoa tốt nghiệp đã chào mừng các giảng viên, cựu sinh viên và phụ huynh đến hội trường lớn của trường đại học.", ["second-ranked student"], ["class salutatorian"], "Salute: speak salutatory welcome"),
    ],
    "Shopping, Fashion & Retail": [
        ("athleisure", "/æθˈliːʒər/", "n", "thời trang thể thao ứng dụng dạo phố", "comfortable and casual clothing designed to be worn both for exercising and as everyday wear", "The global rise of remote work boosted luxury athleisure sales worldwide.", "Sự bùng nổ của xu hướng làm việc từ xa trên toàn cầu đã thúc đẩy doanh số thời trang thể thao dạo phố cao cấp trên toàn thế giới.", ["sportswear fashion"], ["athleisure trend", "athleisure apparel"], "Athletic + leisure wear"),
        ("haberdasher", "/ˈhæbərdæʃər/", "n", "người bán phụ kiện trang phục nam", "a dealer in men's clothing and small tailoring accessories", "The master haberdasher fitted the groom with bespoke silk braces and cufflinks.", "Người bán phụ kiện nam bậc thầy đã chuẩn bị cho chú rể bộ dây đeo quần bằng lụa và khuy măng sét may đo riêng.", ["clothier"], ["custom haberdasher"], "Dealer in small fine accessories"),
    ],
    "Emotions, Personality & Character": [
        ("sanguine", "/ˈsæŋɡwɪn/", "adj", "lạc quan vui tươi, tràn đầy niềm tin", "optimistic or positive, especially in an apparently bad or difficult situation", "Despite the bleak fiscal forecast, the CEO remained remarkably sanguine.", "Bất chấp dự báo tài chính ảm đạm, vị tổng giám đốc điều hành vẫn tỏ ra hết sức lạc quan.", ["optimistic", "cheerful", "buoyant"], ["sanguine temperament", "sanguine outlook"], "Sanguis = warm blood optimistic nature"),
        ("punctilious", "/pʌŋkˈtɪliəs/", "adj", "chu đáo kỹ tính từng li từng tí", "showing great attention to detail or correct behavior and formal etiquette", "The diplomatic butler was punctilious about royal table manners and protocol.", "Người quản gia ngoại giao cực kỳ chu đáo kỹ tính về các quy tắc bàn ăn và nghi lễ hoàng gia.", ["meticulous", "scrupulous", "exacting"], ["punctilious host", "punctilious observance"], "Punctum = dot/point of detail"),
        ("pusillanimous", "/ˌpjuːsɪˈlænɪməs/", "adj", "nhát gan, hèn nhát thiếu dũng khí", "showing a lack of courage or determination; timid", "The committee criticized the director's pusillanimous refusal to confront corruption.", "Ủy ban đã chỉ trích sự từ chối hèn nhát thiếu dũng khí của viên giám đốc khi không dám đối đầu với nạn tham nhũng.", ["cowardly", "spineless", "timid"], ["pusillanimous retreat", "pusillanimous decision"], "Pusillus (very small) + animus (soul/spirit)"),
    ],
    "Family, Relationships & Society": [
        ("cohabitation", "/ˌkoʊhæbɪˈteɪʃən/", "n", "sự chung sống không kết hôn, sống thử", "the state of living together and having a sexual relationship without being married", "Sociologists documented the rising prevalence of millennial couples opting for long-term cohabitation.", "Các nhà xã hội học đã ghi nhận sự gia tăng phổ biến của các cặp đôi trẻ lựa chọn sống thử lâu dài thay vì kết hôn sớm.", ["living together", "domestic partnership"], ["unmarried cohabitation", "premarital cohabitation"], "Co (together) + habitare (dwell)"),
        ("consanguinity", "/ˌkɒnsæŋˈɡwɪnəti/", "n", "mối quan hệ huyết thống cùng chung dòng máu", "the fact of being descended from the same ancestor; blood relationship", "Genetic counselors assess the degree of consanguinity in hereditary risk screenings.", "Các chuyên gia tư vấn di truyền đánh giá mức độ quan hệ huyết thống trong các đợt sàng lọc nguy cơ bệnh lý bẩm sinh.", ["blood kinship", "lineage link"], ["degrees of consanguinity", "close consanguinity"], "Con (with) + sanguis (blood)"),
        ("fraternization", "/ˌfrætərnaɪˈzeɪʃən/", "n", "sự kết giao thân mật (giữa các cấp/phe phái)", "friendly association with someone, especially when not allowed by protocol or military command", "Military regulations strictly prohibit fraternization between commanding officers and enlisted personnel.", "Kỷ luật quân đội nghiêm cấm việc kết giao thân mật giữa các sĩ quan chỉ huy và binh sĩ cấp dưới.", ["fraternizing", "informal mingling"], ["prohibit fraternization", "rules on fraternization"], "Frater = brotherly association"),
    ],
    "Media, News & Communication": [
        ("clickbait", "/ˈklɪkbeɪt/", "n", "nội dung giật gân câu view câu nhấp chuột", "content whose main purpose is to attract attention and encourage visitors to click on a link to a webpage", "Reputable journals avoid cheap clickbait headlines to safeguard reader trust.", "Các tờ báo uy tín tránh sử dụng các tiêu đề giật gân câu view rẻ tiền để bảo vệ niềm tin của độc giả.", ["link bait", "sensational teaser"], ["clickbait headline", "avoid clickbait"], "Baiting clicks with sensational words"),
        ("paywall", "/ˈpeɪwɔːl/", "n", "tường thu phí đọc báo điện tử", "a digital feature on a website that restricts access to content via a paid subscription", "The Financial Times operates a rigid metered paywall for in-depth editorial investigations.", "Tờ Financial Times vận hành một bức tường thu phí có giới hạn bài đọc nghiêm ngặt đối với các bài điều tra chuyên sâu.", ["subscription gate"], ["metered paywall", "behind a paywall"], "Wall demanding payment to enter"),
        ("hyperbole", "/haɪˈpɜːrbəli/", "n", "phép nói quá, cường điệu hóa thông tin", "exaggerated statements or claims not meant to be taken literally", "Tabloid headlines rely on theatrical hyperbole to sell paper copies on newsstands.", "Tiêu đề của các tờ báo lá cải dựa vào nghệ thuật cường điệu hóa kịch tính để bán báo in tại các sạp báo.", ["exaggeration", "overstatement"], ["media hyperbole", "sheer hyperbole"], "Hyper (beyond) + ballein (throw)"),
        ("muckraking", "/ˈmʌkˌreɪkɪŋ/", "n", "nghề báo phanh phui bê bối góc khuất xã hội", "the searching out and publicizing of scandalous information about famous people or corrupt institutions", "Early twentieth-century muckraking journalists exposed dangerous industrial meatpacking scandals.", "Các nhà báo chuyên phanh phui góc khuất đầu thế kỷ XX đã vạch trần các bê bối chế biến thịt công nghiệp nguy hiểm.", ["investigative muckraking", "whistleblowing journalism"], ["tradition of muckraking", "muckraking reporter"], "Raking up muck and dirt to light"),
        ("wire-service", "/ˈwaɪər ˌsɜːrvɪs/", "n", "hãng thông tấn xã phát tin toàn cầu", "a news agency that supplies syndicated news by wire or internet to newspapers and broadcasters", "Global newsrooms subscribe to wire-service bulletins from Reuters and the Associated Press.", "Các tòa soạn báo trên khắp thế giới đăng ký nhận bản tin từ các hãng thông tấn xã như Reuters và Associated Press.", ["news agency", "press syndicate"], ["international wire-service", "wire-service dispatch"], "Telegraph wire news distribution service"),
    ],
    "Law, Crime & Justice": [
        ("embezzlement", "/ɪmˈbɛzlmənt/", "n", "tội tham ô biển thủ công quỹ", "theft or misappropriation of funds placed in one's trust or belonging to one's employer", "The chief accountant faced twenty years imprisonment for corporate embezzlement.", "Kế toán trưởng đối mặt với án phạt 20 năm tù vì tội tham ô và biển thủ công quỹ doanh nghiệp.", ["misappropriation", "peculation", "defalcation"], ["charged with embezzlement", "large-scale embezzlement"], "Embezzle: stole entrusted funds"),
        ("indictment", "/ɪnˈdaɪtmənt/", "n", "bản cáo trạng hình sự chính thức", "a formal charge or accusation of a serious crime issued by a grand jury", "The federal grand jury returned a twelve-count criminal indictment against the fraudulent executive.", "Bồi thẩm đoàn liên bang đã đưa ra bản cáo trạng hình sự gồm 12 tội danh chống lại viên giám đốc điều hành gian lận.", ["formal charge", "prosecution"], ["unseal an indictment", "criminal indictment"], "Indict: formally charge in court"),
        ("statute", "/ˈstætʃuːt/", "n", "đạo luật thành văn của quốc hội", "a written law passed by a legislative body at the national or state level", "The federal environmental protection statute regulates chemical waste discharge into rivers.", "Đạo luật thành văn về bảo vệ môi trường của liên bang quy định việc xả thải hóa chất vào các dòng sông.", ["legislative act", "enactment"], ["statute of limitations", "federal statute"], "Statute: set in legal stone"),
        ("culpability", "/ˌkʌlpəˈbɪləti/", "n", "trách nhiệm hình sự, tính có lỗi", "responsibility for a fault or wrong; blameworthiness under criminal statutes", "The defense attorney argued that mental incapacity diminished the defendant's legal culpability.", "Luật sư bào chữa lập luận rằng việc suy giảm năng lực hành vi đã làm giảm nhẹ trách nhiệm hình sự của bị cáo.", ["guilt", "blameworthiness", "liability"], ["establish culpability", "admit culpability"], "Culpa = guilt/fault in Latin"),
        ("injunction", "/ɪnˈdʒʌŋkʃən/", "n", "lệnh cấm / chế tài khẩn cấp của tòa án", "an authoritative warning or judicial order restraining a person from beginning or continuing an action", "The tech giant secured an emergency injunction freezing the sale of infringing copycat devices.", "Tập đoàn công nghệ đã xin được lệnh cấm khẩn cấp của tòa án nhằm đóng băng việc buôn bán các thiết bị sao chép vi phạm bản quyền.", ["court order", "restraining order"], ["grant an injunction", "seek an injunction"], "Injoin: court ordering to halt action"),
    ],
    "Politics, Diplomacy & Global Affairs": [
        ("sanction", "/ˈsæŋkʃən/", "n", "biện pháp trừng phạt kinh tế quốc tế", "a threatened penalty for disobeying a law or rule, especially trade restrictions imposed by nations", "The United Nations Security Council voted to impose targeted international economic sanctions.", "Hội đồng Bảo an Liên hợp quốc đã bỏ phiếu áp đặt các biện pháp trừng phạt kinh tế quốc tế có mục tiêu.", ["economic embargo", "trade penalty"], ["impose sanctions", "lift sanctions"], "Sanctio: legal decree of punishment"),
        ("autocracy", "/ɔːˈtɒkrəsi/", "n", "chế độ chuyên quyền độc tài", "a system of government by one person with absolute power", "Civil liberties and independent courts were dismantled under the authoritarian autocracy.", "Các quyền tự do dân sự và tòa án độc lập đã bị giải thể dưới chế độ chuyên quyền độc tài toàn trị.", ["absolutism", "dictatorship", "tyranny"], ["military autocracy", "despotic autocracy"], "Auto (self) + kratos (power)"),
        ("demagogue", "/ˈdɛməɡɒɡ/", "n", "kẻ mị dân lợi dụng cảm xúc đám đông", "a political leader who seeks support by appealing to the desires and prejudices of ordinary people rather than by using rational argument", "The populist demagogue mobilized crowds by stoking fear of foreign adversaries.", "Kẻ mị dân theo chủ nghĩa dân túy đã kích động đám đông bằng cách thổi bùng nỗi sợ hãi về các thế lực thù địch bên ngoài.", ["rabble-rouser", "populist agitator"], ["populist demagogue", "beware of demagogues"], "Demos (people) + agogos (leader)"),
        ("theocracy", "/θiˈɒkrəsi/", "n", "chế độ thần quyền", "a system of government in which priests or religious authorities rule in the name of God", "In that medieval theocracy, religious law superseded civil and commercial codes.", "Tại nhà nước thần quyền thời Trung Cổ đó, giáo luật tôn giáo có giá trị cao hơn cả các bộ luật dân sự và thương mại.", ["religious rule"], ["clerical theocracy", "fundamentalist theocracy"], "Theos (god) + kratos (power)"),
        ("envoy", "/ˈɛnvɔɪ/", "n", "đặc sứ ngoại giao", "a messenger or representative, especially one on a diplomatic mission", "The president dispatched a special envoy to mediate peace talks in the volatile border region.", "Tổng thống đã cử một đặc sứ ngoại giao đặc biệt đến làm trung gian cho các cuộc đàm phán hòa bình ở khu vực biên giới bất ổn.", ["diplomat", "emissary", "delegate"], ["special diplomatic envoy", "peace envoy"], "Envoyer = send on mission in French"),
        ("sovereign", "/ˈsɒvrɪn/", "adj", "có chủ quyền độc lập hoàn toàn", "possessing supreme or ultimate political and legal power within a territory", "The island republic celebrated fifty years of recognized sovereign self-governance.", "Nước cộng hòa đảo quốc đã kỷ niệm 50 năm nền tự quản có chủ quyền độc lập được quốc tế công nhận.", ["autonomous", "independent"], ["sovereign state", "sovereign nation"], "Sovereign: supreme ruler status"),
        ("annexation", "/ˌænɛkˈseɪʃən/", "n", "sự thôn tính sáp nhập lãnh thổ", "the action of annexing something, especially territory seized by force", "International bodies condemned the illegal military annexation of the border province.", "Các tổ chức quốc tế đã kịch liệt lên án hành động thôn tính sáp nhập quân sự bất hợp pháp đối với tỉnh biên giới.", ["territorial conquest", "seizure"], ["unlawful annexation", "condemn annexation"], "Ad (to) + nectere (bind/attach)"),
    ],
    "Science, Space & Astronomy": [
        ("astrophysics", "/ˌæstroʊˈfɪzɪks/", "n", "vật lý thiên văn", "the branch of astronomy concerned with the physical nature of stars and other celestial bodies", "Modern astrophysics relies on computational simulations of dark matter galactic halos.", "Vật lý thiên văn hiện đại dựa vào các mô phỏng máy tính về quầng vật chất tối của thiên hà.", ["stellar physics"], ["study astrophysics", "theoretical astrophysics"], "Astro (star) + physics"),
        ("cosmology", "/kɒzˈmɒlədʒi/", "n", "vũ trụ học", "the science of the origin and development of the universe from the Big Bang onwards", "Cosmology examines the accelerating cosmic expansion driven by dark energy.", "Vũ trụ học nghiên cứu sự giãn nở ngày càng tăng tốc của vũ trụ do năng lượng tối thúc đẩy.", ["universe science"], ["modern cosmology", "cosmological model"], "Cosmos (universe) + logy"),
        ("interferometer", "/ˌɪntərfəˈrɒmɪtər/", "n", "giao thoa kế quang học / sóng hấp dẫn", "an instrument in which the interference of waves is used to make precise measurements", "The LIGO laser interferometer detected ripples in spacetime from colliding neutron stars.", "Giao thoa kế laser LIGO đã phát hiện ra các gợn sóng trong không-thời gian từ các vụ va chạm sao neutron.", ["optical measuring device"], ["laser interferometer", "astronomical interferometer"], "Interference + meter"),
        ("perihelion", "/ˌpɛrɪˈhiːliən/", "n", "điểm cận nhật (điểm gần mặt trời nhất)", "the point in the orbit of a planet, asteroid, or comet at which it is closest to the sun", "The comet brightened dramatically as it swung around perihelion inside Mercury's orbit.", "Sao chổi đã sáng bừng lên một cách ngoạn mục khi nó bay quanh điểm cận nhật bên trong quỹ đạo của Sao Thủy.", ["closest solar approach"], ["reach perihelion", "orbital perihelion"], "Peri (near) + helios (sun)"),
        ("aphelion", "/æfˈhiːliən/", "n", "điểm viễn nhật (điểm xa mặt trời nhất)", "the point in the orbit of a planet, asteroid, or comet at which it is furthest from the sun", "Earth reaches its annual aphelion in early July when orbital speed is slowest.", "Trái Đất đạt đến điểm viễn nhật hàng năm vào đầu tháng 7 khi tốc độ quay trên quỹ đạo là chậm nhất.", ["furthest solar point"], ["earth at aphelion", "annual aphelion"], "Apo (away from) + helios (sun)"),
        ("equinox", "/ˈiːkwɪnɒks/", "n", "điểm phân (xuân phân hoặc thu phân, ngày đêm bằng nhau)", "the time or date at which the sun crosses the celestial equator, when day and night are of equal length", "Agricultural societies timed spring planting with the arrival of the vernal equinox.", "Các xã hội nông nghiệp xưa đã canh thời gian gieo hạt vụ xuân theo thời điểm diễn ra tiết xuân phân.", ["equal day and night"], ["vernal equinox", "autumnal equinox"], "Aequus (equal) + nox (night)"),
        ("magnetosphere", "/mæɡˈniːtəˌsfɪər/", "n", "từ quyển của hành tinh", "the region surrounding an astronomical body in which its magnetic field is the predominant magnetic field", "Earth's protective magnetosphere deflects lethal solar wind radiation and cosmic rays.", "Từ quyển bảo vệ của Trái Đất làm chệch hướng các bức xạ gió mặt trời và tia vũ trụ chết người.", ["magnetic envelope"], ["planetary magnetosphere", "geomagnetic magnetosphere"], "Magnet + sphere"),
        ("supercluster", "/ˈsuːpərˌklʌstər/", "n", "siêu đám thiên hà trong vũ trụ", "a large group of smaller galaxy clusters or galaxy groups, among the largest structures in the universe", "Our Milky Way belongs to the vast Laniakea supercluster comprising one hundred thousand galaxies.", "Dải Ngân Hà của chúng ta thuộc về siêu đám thiên hà Laniakea khổng lồ bao gồm một trăm nghìn thiên hà.", ["mega galactic cluster"], ["galaxy supercluster", "Laniakea supercluster"], "Super + cluster of galaxies"),
        ("zenith", "/ˈzɛnɪθ/", "n", "điểm thiên đỉnh (điểm cao nhất ngay trên đỉnh đầu)", "the point in the sky directly above an observer", "At local noon in the tropics, the blazing sun stands directly overhead at the zenith.", "Vào giữa trưa tại vùng nhiệt đới, mặt trời rực lửa nằm ngay phía trên điểm thiên đỉnh.", ["highest celestial point", "apex"], ["reach the zenith", "at the zenith"], "Samt = path over head in Arabic"),
        ("spectrograph", "/ˈspɛktrəˌɡræf/", "n", "máy quang phổ ghi hình ảnh vạch quang phổ", "an apparatus for photographing or otherwise recording spectra for astronomical composition analysis", "Telescopes utilize a high-dispersion cryogenic spectrograph to analyze exoplanet atmospheres.", "Kính viễn vọng sử dụng máy quang phổ nhiệt độ cực thấp có độ phân tán cao để phân tích bầu khí quyển của các hành tinh ngoài hệ mặt trời.", ["optical spectrograph"], ["echelle spectrograph", "astronomical spectrograph"], "Spectrum + graph"),
        ("cosmogony", "/kɒzˈmɒɡəni/", "n", "nguồn gốc luận về sự hình thành vũ trụ", "the branch of science or a theory concerning the origin of the universe or solar system", "Ancient myths and modern astrophysical inflation theories offer contrasting cosmogonies.", "Các thần thoại cổ xưa và thuyết lạm phát vật lý thiên văn hiện đại đưa ra những nguồn gốc luận tương phản nhau về vũ trụ.", ["origin of universe"], ["stellar cosmogony", "modern cosmogony"], "Cosmos (universe) + gonia (begetting/origin)"),
    ],
    "Architecture, Housing & Real Estate": [
        ("architrave", "/ˈɑːrkɪˌtreɪv/", "n", "dầm vòm ngang đè trên đầu cột", "the lowest part of a classical entablature resting directly on the column capitals", "The Doric temple featured an unadorned limestone architrave spanning between majestic pillars.", "Ngôi đền phong cách Doric nổi bật với dầm vòm ngang bằng đá vôi mộc mạc bắc ngang giữa những cây cột uy nghiêm.", ["epistyle", "lintel beam"], ["molded architrave", "classical architrave"], "Archi (chief) + trabs (beam)"),
        ("atrium", "/ˈeɪtriəm/", "n", "giếng trời trung tâm thông tầng", "an open-roofed central hall in an ancient Roman house, or modern multi-story glass-roofed court", "The corporate headquarters features a sunlit seven-story glass atrium filled with trees.", "Trụ sở công ty có một giếng trời trung tâm thông tầng bằng kính cao 7 tầng tràn ngập ánh nắng và cây xanh.", ["central skylight hall", "courtyard"], ["glass atrium", "sunlit atrium"], "Atrium ancient Roman open hall"),
        ("buttress", "/ˈbʌtrɪs/", "n", "trụ áp tường chịu lực kiến trúc Gothic", "a projecting support of stone or brick built against a wall to reinforce it", "Cathedral builders designed flying buttresses to support soaring vaulted stone ceilings.", "Các thợ xây nhà thờ đã thiết kế các trụ áp tường bay để nâng đỡ những trần nhà vòm đá cao vút.", ["reinforcement", "pier", "prop"], ["flying buttress", "stone buttress"], "Buttress supporting load-bearing walls"),
        ("cupola", "/ˈkjuːpələ/", "n", "mái vòm tròn nhỏ trên đỉnh tòa nhà", "a small dome, especially a small dome on a drum on top of a larger dome, adorning a roof", "Tourists climbed steep spiral stairs into the copper cupola to gaze out at the city skyline.", "Khách du lịch leo lên những bậc thang xoắn ốc dốc đứng để vào mái vòm đồng nhỏ ngắm nhìn toàn cảnh đường chân trời thành phố.", ["lantern dome", "turret dome"], ["rooftop cupola", "copper cupola"], "Cupola small cup-shaped dome"),
        ("lintel", "/ˈlɪntl/", "n", "thanh lanh-tô ngang đỡ phía trên cửa đi/cửa sổ", "a horizontal support of timber, stone, concrete, or steel across the top of a door or window", "Carved hieroglyphics decorated the granite lintel above the entrance to the pharaoh's tomb.", "Những ký tự tượng hình chạm khắc trang trí thanh lanh-tô bằng đá granit phía trên lối vào lăng mộ pharaoh.", ["horizontal crossbeam"], ["granite lintel", "structural lintel"], "Lintel supporting opening above door"),
        ("pergola", "/ˈpɜːrɡələ/", "n", "giàn hoa leo che nắng ngoài vườn", "an arched structure in a garden consisting of a framework covered with climbing plants", "Homeowners dined under a wooden pergola draped with fragrant wisteria vines.", "Chủ nhà dùng bữa tối dưới giàn hoa leo bằng gỗ phủ đầy những chùm hoa tử đằng ngát hương.", ["arbor", "trellis canopy"], ["garden pergola", "shaded pergola"], "Pergula = projecting roof/vine framework"),
        ("balustrade", "/ˌbæləˈstreɪd/", "n", "dãy con tiện lan can ban công/cầu thang", "a railing supported by balusters, especially one forming an ornamental parapet to a balcony", "Marble balustrades flanked the ceremonial grand staircase inside the opera house.", "Những hàng con tiện lan can bằng đá cẩm thạch chạy dọc hai bên cầu thang lớn bên trong nhà hát opera.", ["railing", "parapet barrier"], ["ornate balustrade", "marble balustrade"], "Baluster-supported ornamental railing"),
    ],
    "Job Interview & Career Development": [
        ("probation", "/proʊˈbeɪʃən/", "n", "thời gian thử việc đánh giá năng lực", "a period of trial to assess a person's suitability for a permanent job role", "New software hires typically undergo a three-month technical probation period.", "Các kỹ sư phần mềm mới thường trải qua thời gian thử việc kỹ thuật kéo dài ba tháng.", ["trial period", "evaluation term"], ["probationary period", "pass probation"], "Probare = to test/prove ability"),
        ("appraisal", "/əˈpreɪzəl/", "n", "sự thẩm định đánh giá hiệu quả công việc định kỳ", "a formal assessment, typically in an interview, of the performance of an employee over a period", "The annual employee performance appraisal determines merit salary adjustments and promotions.", "Đợt thẩm định đánh giá hiệu quả công việc hàng năm quyết định các đợt tăng lương theo năng lực và thăng chức.", ["evaluation", "review"], ["annual appraisal", "performance appraisal"], "Appraise worth and contributions"),
        ("severance", "/ˈsɛvərəns/", "n", "trợ cấp thôi việc, gói đền bù chấm dứt hợp đồng", "an amount of money paid by an employer to an employee upon involuntary termination of employment", "Laid-off staff received six months of salary and extended healthcare in their severance package.", "Những nhân viên bị cắt giảm biên chế đã nhận được sáu tháng lương cùng gói bảo hiểm y tế gia hạn trong gói trợ cấp thôi việc.", ["separation pay", "redundancy compensation"], ["severance package", "receive severance"], "Sever ties with company settlement"),
    ],
    "Marketing, Advertising & Branding": [
        ("billboard", "/ˈbɪlˌbɔːrd/", "n", "biển quảng cáo tấm lớn ngoài trời", "a large outdoor board for displaying advertisements alongside highways and busy urban centers", "The luxury watchmaker rented digital billboards overlooking Times Square in New York.", "Hãng đồng hồ xa xỉ đã thuê các biển quảng cáo kỹ thuật số tấm lớn nhìn ra Quảng trường Thời đại ở New York.", ["hoarding", "outdoor display"], ["digital billboard", "highway billboard"], "Board showing advertising bills"),
        ("copywriting", "/ˈkɒpiˌraɪtɪŋ/", "n", "nghề viết lời quảng cáo sáng tạo nội dung", "the act or occupation of writing text for the purpose of advertising or other forms of marketing", "Compelling copywriting on the landing page turned casual visitors into paying customers.", "Những lời văn quảng cáo thuyết phục trên trang đích đã biến những người ghé thăm thông thường thành khách hàng trả phí.", ["ad writing", "content crafting"], ["persuasive copywriting", "freelance copywriting"], "Writing the advertising copy"),
        ("endorsement", "/ɪnˈdɔːrsmənt/", "n", "sự bảo chứng thương hiệu từ người nổi tiếng", "an act of giving one's public approval or support to someone or something, especially in advertising", "The sports superstar signed a fifty-million-dollar footwear brand endorsement contract.", "Siêu sao thể thao đã ký hợp đồng bảo chứng thương hiệu giày dép trị giá 50 triệu đô la.", ["celebrity testimonial"], ["celebrity endorsement", "brand endorsement"], "Endorsing a product by signing name"),
        ("merchandising", "/ˈmɜːrtʃəndaɪzɪŋ/", "n", "nghiệp vụ trưng bày và bán sản phẩm lưu niệm", "the activity of promoting the sale of goods, especially by their presentation in retail stores", "Movie studios generate substantial revenue from licensed toy and apparel merchandising.", "Các hãng phim thu về doanh thu đáng kể từ nghiệp vụ bán đồ chơi và quần áo lưu niệm được cấp phép.", ["retail presentation"], ["visual merchandising", "licensed merchandising"], "Merchandise display and sales tactics"),
        ("sponsorship", "/ˈspɒnsərʃɪp/", "n", "sự tài trợ thương hiệu cho sự kiện", "financial support given by an entity to a sports event, cultural festival, or public figure", "Global energy corporations provided major corporate sponsorship for the international marathon.", "Các tập đoàn năng lượng toàn cầu đã cung cấp tài trợ lớn cho giải chạy marathon quốc tế.", ["financial backing"], ["corporate sponsorship", "event sponsorship"], "Sponsoring events for brand prestige"),
        ("leaflet", "/ˈliːflɪt/", "n", "tờ rơi quảng cáo cầm tay", "a printed sheet of paper containing information or advertising and usually distributed free", "Volunteers handed out colorful leaflets highlighting the local artisan farmer's market.", "Các tình nguyện viên đã phát những tờ rơi nhiều màu sắc quảng bá về chợ nông sản thủ công địa phương.", ["flyer", "pamphlet"], ["distribute leaflets", "promotional leaflet"], "Small leaf of printed paper"),
        ("brand-equity", "/ˈbrænd ˌɛkwəti/", "n", "tài sản thương hiệu (giá trị vô hình tạo ra từ niềm tin)", "the commercial value that derives from consumer perception of the brand name rather than the product itself", "Apple's extraordinary brand-equity allows it to command industry-leading profit margins.", "Tài sản thương hiệu vượt trội của Apple cho phép hãng có được biên lợi nhuận dẫn đầu ngành.", ["brand value", "reputational capital"], ["strong brand-equity", "build brand-equity"], "Equity capital built into brand recognition"),
        ("guerrilla-marketing", "/ɡəˈrɪlə ˌmɑːrkɪtɪŋ/", "n", "tiếp thị du kích (sáng tạo bất ngờ, kinh phí thấp)", "innovative, unconventional, and low-cost marketing techniques aimed at obtaining maximum exposure", "The indie movie used guerrilla-marketing, staging flash mobs in major subway stations.", "Bộ phim độc lập đã áp dụng chiến thuật tiếp thị du kích bằng cách tổ chức các màn nhảy flashmob bất ngờ tại các ga tàu điện ngầm lớn.", ["unconventional promotion"], ["clever guerrilla-marketing", "guerrilla-marketing stunt"], "Guerrilla ambush surprise tactics in marketing"),
        ("advertorial", "/ˌædvərˈtɔːriəl/", "n", "bài viết quảng cáo trá hình bài báo", "a newspaper or magazine advertisement written in the style of an objective news article", "The wellness company sponsored a full-page advertorial detailing the science of hydration.", "Công ty chăm sóc sức khỏe đã tài trợ một bài viết quảng cáo nguyên trang mô tả chi tiết về khoa học cấp nước.", ["sponsored article", "native ad"], ["published advertorial", "sponsor an advertorial"], "Advertisement + editorial"),
    ],
    "Logistics, Supply Chain & E-commerce": [
        ("chassis", "/ˈʃæsi/", "n", "khung gầm sơ-mi rơ-moóc kéo container", "the base frame of a wheeled vehicle used in freight trucking to transport ocean shipping containers", "Port drayage drivers waited hours to secure an empty container chassis for pickup.", "Các tài xế vận chuyển cảng đã phải chờ đợi nhiều giờ để có được khung gầm sơ-mi rơ-moóc trống để nhận hàng.", ["trailer frame", "undercarriage"], ["container chassis", "chassis pool"], "Chassis structural wheel frame"),
        ("drayage", "/ˈdreɪɪdʒ/", "n", "vận chuyển hàng cự ly ngắn từ cảng về kho", "the transport of goods over a short distance in the shipping and logistics industries", "Electric trucks are revolutionizing local port drayage by eliminating diesel tailpipe emissions.", "Xe tải điện đang cách mạng hóa dịch vụ vận chuyển hàng cự ly ngắn từ cảng về kho bằng cách loại bỏ khí thải diesel.", ["short-haul trucking"], ["port drayage", "intermodal drayage"], "Dray cart haulage over short miles"),
        ("stevedore", "/ˈstiːvədɔːr/", "n", "công nhân bốc xếp cảng biển", "a person employed at a dock to load and unload ships", "Veteran stevedores operated heavy gantry cranes to offload container ships efficiently.", "Những công nhân bốc xếp cảng biển kỳ cựu đã vận hành cần cẩu giàn hạng nặng để dỡ hàng nhanh chóng.", ["dockworker", "longshoreman"], ["union stevedores", "experienced stevedore"], "Estivador: one who packs cargo in ship"),
        ("wharfage", "/ˈwɔːrfɪdʒ/", "n", "phí sử dụng cầu cảng neo đậu", "a charge incurred for using a wharf or quay for loading or unloading cargo", "Port authorities updated wharfage tariffs for vessels staying longer than seventy-two hours.", "Cơ quan quản lý cảng đã cập nhật biểu phí sử dụng cầu cảng cho các tàu thuyền lưu lại quá 72 giờ.", ["dock fee", "quayage"], ["wharfage fee", "port wharfage"], "Wharf usage dues"),
        ("tare-weight", "/ˈtɛər weɪt/", "n", "trọng lượng vỏ rỗng của phương tiện / bao bì", "the weight of an empty vehicle or container, deducted from gross weight to obtain net weight of cargo", "Weigh stations subtract the tare-weight of the trailer to calculate the exact grain payload.", "Các trạm cân xe trừ trọng lượng vỏ rỗng của rơ-moóc để tính toán chính xác trọng lượng tịnh của hàng ngũ cốc.", ["empty container weight"], ["tare-weight certification", "calculate tare-weight"], "Tare empty shell deduction"),
        ("dunnage", "/ˈdʌnɪdʒ/", "n", "vật liệu chèn lót bảo vệ hàng trong khoang tàu", "loose wood, matting, or inflatable airbags used to protect cargo during an ocean voyage", "Inflatable dunnage air bags prevent pallets from shifting inside shipping containers at sea.", "Túi khí chèn lót hàng bằng vật liệu dunnage ngăn các pallet xô lệch bên trong container trên biển.", ["cargo cushioning", "padding"], ["dunnage bags", "protective dunnage"], "Dunnage scrap wood and air cushions"),
        ("demurrage-fee", "/dɪˈmɜːrɪdʒ fiː/", "n", "phí phạt lưu bãi container quá hạn quy định", "a specific financial penalty charged for exceeding the permitted free time at a container terminal", "Importers scrambled to clear customs to avoid racking up exorbitant daily demurrage-fees.", "Các nhà nhập khẩu hối hả hoàn tất thủ tục hải quan để tránh phải chịu các khoản phí phạt lưu bãi đắt đỏ.", ["detention fee"], ["pay demurrage-fee", "daily demurrage-fee"], "Demur penalty fees"),
        ("bill-of-entry", "/ˌbɪl əv ˈɛntri/", "n", "tờ khai hải quan nhập khẩu chính thức", "a formal legal declaration made by an importer describing goods entering national borders", "The clearing agent submitted the validated bill-of-entry to the customs boundary official.", "Đại lý thông quan đã đệ trình tờ khai hải quan nhập khẩu đã được phê duyệt cho cơ quan kiểm soát biên giới.", ["customs declaration"], ["file a bill-of-entry", "stamped bill-of-entry"], "Bill documenting entry of cargo"),
    ],
    "Hospitality, Hotel & Customer Service": [
        ("all-inclusive", "/ˌɔːl ɪnˈkluːsɪv/", "adj", "trọn gói bao gồm mọi dịch vụ (ăn uống, nghỉ dưỡng)", "including accommodation, food, drinks, and activities in the upfront price", "Couples booked a Caribbean all-inclusive resort for a stress-free honeymoon getaway.", "Các cặp đôi đã đặt kỳ nghỉ trọn gói tại một khu nghỉ dưỡng Caribe cho tuần trăng mật thảnh thơi.", ["fully packaged"], ["all-inclusive resort", "all-inclusive vacation"], "All amenities included in one bill"),
        ("en-suite", "/ˌɒn ˈswiːt/", "adj", "phòng tắm khép kín gắn liền phòng ngủ", "of a bathroom, immediately adjoining and accessed directly from a bedroom", "Each deluxe master bedroom in the villa boasts a spacious private en-suite bathroom.", "Mỗi phòng ngủ lớn cao cấp trong biệt thự đều sở hữu một phòng tắm khép kín riêng biệt rộng rãi.", ["attached bathroom"], ["en-suite bathroom", "en-suite shower"], "En suite: in suite sequence directly"),
        ("courtesy-shuttle", "/ˈkɜːrtəsi ˌʃʌtl/", "n", "xe trung chuyển miễn phí của khách sạn", "a complimentary vehicle service taking guests between an airport and a hotel", "The hotel operates a 24-hour courtesy-shuttle leaving every thirty minutes from terminal two.", "Khách sạn vận hành một tuyến xe trung chuyển miễn phí 24/7 khởi hành 30 phút một chuyến từ nhà ga số 2.", ["hotel shuttle", "transfer bus"], ["take the courtesy-shuttle", "airport courtesy-shuttle"], "Courtesy: free of courtesy transfer"),
        ("wake-up-call", "/ˈweɪk ʌp ˌkɔːl/", "n", "cuộc gọi báo thức khách sạn", "a telephone call made by a hotel desk to awaken a sleeping guest at a requested morning hour", "The business traveler requested an early five-thirty wake-up-call before catching his dawn flight.", "Doanh nhân đã yêu cầu một cuộc gọi báo thức sớm lúc 5:30 sáng trước khi kịp chuyến bay bình minh.", ["morning alarm call"], ["order a wake-up-call", "receive a wake-up-call"], "Call to wake up guest"),
        ("no-show", "/ˈnoʊ ʃoʊ/", "n", "khách đặt phòng/bàn nhưng không đến mà không báo hủy", "a person who reserves a room, table, or seat but neither arrives nor cancels beforehand", "The restaurant charges a non-refundable twenty-dollar fee for unnotified dinner no-shows.", "Nhà hàng thu khoản phí 20 đô la không hoàn lại đối với những trường hợp khách vắng mặt không báo hủy trước.", ["absent guest"], ["hotel no-show", "no-show penalty"], "No show: person who did not show up"),
        ("turn-key", "/ˈtɜːrnkiː/", "adj", "chìa khóa trao tay (sẵn sàng sử dụng ngay)", "fully equipped and ready for immediate operation or occupation upon handover", "The developer offered luxury turn-key serviced apartments with complete bespoke furnishings.", "Chủ đầu tư cung cấp các căn hộ dịch vụ cao cấp chìa khóa trao tay với nội thất thiết kế riêng hoàn chỉnh.", ["move-in ready"], ["turn-key apartment", "turn-key suite"], "Just turn key and enter living"),
        ("guest-relations", "/ˌɡɛst rɪˈleɪʃənz/", "n", "bộ phận chăm sóc quan hệ khách hàng", "the department within a hotel dedicated to resolving guest inquiries and ensuring total satisfaction", "The guest-relations manager personally surprised anniversary travelers with champagne.", "Quản lý bộ phận chăm sóc quan hệ khách hàng đã đích thân tạo bất ngờ cho du khách dịp kỷ niệm bằng rượu sâm panh.", ["customer liaison"], ["guest-relations manager", "contact guest-relations"], "Managing relationships with hotel guests"),
        ("overnight-stay", "/ˌoʊvərnaɪt ˈsteɪ/", "n", "chuyến lưu trú qua đêm", "a stay for one or more nights in a lodging establishment", "The spa weekend package included a two-night overnight-stay and thermal hydrotherapy baths.", "Gói dịch vụ spa cuối tuần bao gồm chuyến lưu trú qua hai đêm và các liệu trình thủy trị liệu suối khoáng nóng.", ["hotel stay"], ["comfortable overnight-stay"], "Stay overnight at hotel"),
    ],
    "Culture, Traditions & Festivals": [
        ("acculturation", "/əˌkʌltʃəˈreɪʃən/", "n", "sự giao lưu tiếp biến văn hóa", "assimilation to a different culture, typically the dominant one, while retaining original traits", "Immigrants experience acculturation, blending ancestral customs with new homeland values.", "Những người nhập cư trải qua quá trình tiếp biến văn hóa, kết hợp phong tục tổ tiên với các giá trị quê hương mới.", ["cultural adaptation", "integration"], ["process of acculturation", "cultural acculturation"], "Ac (toward) + culture"),
        ("assimilation", "/əˌsɪmɪˈleɪʃən/", "n", "sự đồng hóa văn hóa hòa nhập toàn diện", "the process of taking in and fully absorbing information, ideas, or the culture of a dominant group", "Historians analyzed the linguistic assimilation of regional dialects into standard national speech.", "Các nhà sử học đã phân tích sự đồng hóa ngôn ngữ của các phương ngữ khu vực vào tiếng phổ thông chuẩn.", ["cultural blending", "absorption"], ["cultural assimilation", "linguistic assimilation"], "Assimilare = make similar"),
        ("ethnocentrism", "/ˌɛθnoʊˈsɛntrɪzəm/", "n", "thuyết vị chủng (coi văn hóa mình là trung tâm)", "evaluation of other cultures according to preconceptions originating in the standards of one's own culture", "Anthropology courses teach students to recognize and overcome unconscious ethnocentrism.", "Các khóa học nhân học dạy sinh viên nhận diện và vượt qua tư tưởng vị chủng văn hóa vô thức.", ["cultural bias"], ["avoid ethnocentrism", "overcome ethnocentrism"], "Ethnos (race/culture) at the center"),
        ("animism", "/ˈænɪmɪzəm/", "n", "thuyết vạn vật hữu linh", "the belief that natural objects, natural phenomena, and the universe possess individual souls", "Indigenous rainforest shamans practice ancient forms of nature animism revering sacred trees.", "Những pháp sư rừng mưa bản địa thực hành các hình thức vạn vật hữu linh cổ xưa tôn thờ cây thiêng.", ["nature spirituality"], ["practice animism", "tribal animism"], "Anima = soul/breath in Latin"),
        ("ancestor-worship", "/ˈænsɛstər ˌwɜːrʃɪp/", "n", "tục thờ cúng tổ tiên", "the custom of venerating deceased ancestors who are considered still to be interested in family affairs", "Traditional Vietnamese families practice ancestor-worship at the altar on Lunar New Year.", "Các gia đình Việt Nam truyền thống thực hành nghi lễ thờ cúng tổ tiên tại bàn thờ vào dịp Tết Nguyên đán.", ["veneration of ancestors"], ["tradition of ancestor-worship"], "Worshiping beloved ancestors"),
        ("oral-history", "/ˌɔːrəl ˈhɪstəri/", "n", "lịch sử truyền khẩu dân gian", "the collection and study of historical information using tape recordings of interviews with people who had personal knowledge of past events", "Scholars archived hours of oral-history recounting life in the highlands during the war.", "Các học giả đã lưu trữ nhiều giờ tư liệu lịch sử truyền khẩu kể lại cuộc sống tại vùng cao trong chiến tranh.", ["spoken records"], ["preserve oral-history", "record oral-history"], "History spoken by word of mouth"),
    ],
    "Hobbies, Leisure & Creative Skills": [
        ("crochet", "/kroʊˈʃeɪ/", "n", "nghệ thuật đan móc len bằng kim móc", "a handicraft in which yarn is made up into a textured fabric by means of a hooked needle", "She spent cozy winter evenings crafting soft woolen blankets using crochet.", "Cô đã dành những buổi tối mùa đông ấm áp để đan móc những tấm chăn len mềm mại bằng kim móc.", ["needlecraft", "hooked knitting"], ["learn crochet", "crochet blanket"], "Croc = hook in French"),
        ("carpentry", "/ˈkɑːrpəntri/", "n", "nghề mộc, nghệ thuật làm đồ gỗ gia dụng", "the activity or skill of making things from wood or repairing wooden objects", "His basement workshop is equipped with chisels and table saws for artisanal carpentry.", "Xưởng dưới tầng hầm của anh được trang bị đục và cưa bàn phục vụ công việc làm mộc thủ công.", ["woodworking", "joinery"], ["fine carpentry", "master carpentry"], "Carpentarius = carriage-maker/woodworker"),
        ("knitting", "/ˈnɪtɪŋ/", "n", "nghệ thuật đan len bằng hai que đan", "the craft of making garments or blankets from yarn using two pointed needles", "Handmade knitting requires steady tension and focus to produce even wool patterns.", "Nghệ thuật đan len thủ công đòi hỏi lực kéo đều tay và sự tập trung để tạo ra các họa tiết len đồng đều.", ["woolwork"], ["hand knitting", "knitting pattern"], "Knit loops together"),
        ("aquascaping", "/ˈækwəˌskeɪpɪŋ/", "n", "nghệ thuật thiết kế thủy sinh bể cá", "the craft of arranging aquatic plants, rocks, and driftwood in an aesthetically pleasing aquarium", "Enthusiasts compete in international contests to build breathtaking underwater aquascaping layouts.", "Những người đam mê tranh tài tại các cuộc thi quốc tế để xây dựng những bố cục thủy sinh dưới nước đẹp mê hồn.", ["underwater landscaping"], ["aquascaping layout", "nature aquascaping"], "Aqua (water) + landscaping"),
        ("leathercraft", "/ˈlɛðərkræft/", "n", "nghệ thuật làm đồ da thủ công", "the skill or hobby of making practical and decorative items out of leather", "Artisans burnish and saddle-stitch durable vegetable-tanned leathercraft wallets.", "Các nghệ nhân đánh bóng mép và khâu yên ngựa những chiếc ví da thủ công thuộc thảo mộc bền đẹp.", ["leatherworking"], ["custom leathercraft", "practice leathercraft"], "Crafting goods from leather"),
        ("diorama", "/ˌdaɪəˈrɑːmə/", "n", "mô hình sa bàn tiểu cảnh thu nhỏ", "a model representing a scene with three-dimensional figures, either in miniature or as a large museum exhibit", "Modelers built a hyper-realistic train station diorama with working miniature lamps.", "Những người chơi mô hình đã dựng một sa bàn tiểu cảnh ga xe lửa siêu thực với đèn đường thu nhỏ sáng rực.", ["scale model", "miniature scene"], ["miniature diorama", "museum diorama"], "Dia (through) + horama (view)"),
        ("glassblowing", "/ˈɡlæsˌbloʊɪŋ/", "n", "nghệ thuật thổi thủy tinh nghệ thuật", "the craft of shaping a mass of molten glass by blowing air into it through a long metal tube", "Master artisans in Venice demonstrate century-old techniques of furnace glassblowing.", "Những nghệ nhân bậc thầy ở Venice phô diễn những kỹ thuật thổi thủy tinh bằng lò nung hàng thế kỷ trước.", ["glass artistry"], ["art of glassblowing", "studio glassblowing"], "Blowing breath into hot molten glass"),
        ("taxidermy", "/ˈtæksɪˌdɜːrmi/", "n", "nghệ thuật nhồi xác ướp tiêu bản động vật", "the art of preparing, stuffing, and mounting the skins of animals with lifelike effect", "Natural history museums display exquisite nineteenth-century taxidermy specimens in glass cases.", "Các bảo tàng lịch sử tự nhiên trưng bày những tiêu bản nhồi xác động vật thế kỷ XIX tinh tế trong tủ kính.", ["mounting specimens"], ["wildlife taxidermy", "study taxidermy"], "Taxis (arrangement) + derma (skin)"),
        ("pottery", "/ˈpɒtəri/", "n", "nghệ thuật làm đồ gốm thủ công", "pots, dishes, and other articles made of earthenware or baked clay", "She finds profound meditative calm when spinning wet clay on the pottery wheel.", "Cô tìm thấy sự tĩnh tâm sâu lắng khi xoay đất sét ướt trên bàn chuốt gốm.", ["ceramics", "stoneware"], ["throw pottery", "handmade pottery"], "Pots made of clay"),
        ("origami-art", "/ˌɒrɪˈɡɑːmi ɑːrt/", "n", "nghệ thuật gấp giấy điêu khắc hình khối", "the refined artistic creation of complex three-dimensional folded paper models", "The Japanese master created tessellated geometric origami-art without using any glue.", "Bậc thầy người Nhật đã tạo ra các tác phẩm nghệ thuật gấp giấy hình học ghép mảng mà không dùng một giọt keo nào.", ["paper sculpture"], ["master origami-art"], "Art of folded paper"),
        ("metal-detecting", "/ˈmɛtl dɪˌtɛktɪŋ/", "n", "thú vui dò tìm kim loại cổ vật", "the activity of searching for buried metal objects using a portable electronic detector", "Beachcombers spend sunrise metal-detecting on shores to discover lost vintage coins.", "Những người đi dọc bãi biển dành cả buổi sớm bình minh để dò kim loại trên bờ nhằm tìm kiếm những đồng xu cổ.", ["treasure hunting"], ["enjoy metal-detecting", "detectorist hobby"], "Detecting metal beneath earth"),
        ("soapmaking", "/ˈsoʊpˌmeɪkɪŋ/", "n", "nghệ thuật tự nấu xà phòng thủ công", "the craft of manufacturing soap at home using natural oils, scents, and lye", "Cold-process soapmaking combines virgin olive oil with soothing lavender essential scents.", "Nghệ thuật nấu xà phòng thủ công ép lạnh kết hợp dầu ô liu nguyên chất với hương tinh dầu oải hương dịu nhẹ.", ["artisan soap craft"], ["cold-process soapmaking"], "Making soaps by hand"),
        ("aeromodelling", "/ˌɛəroʊˈmɒdəlɪŋ/", "n", "thú chơi chế tạo và bay mô hình máy bay", "the activity of building and flying scale models of aircraft", "Father and son shared weekends aeromodelling remote-controlled balsa wood gliders.", "Hai cha con cùng chia sẻ những ngày cuối tuần bên thú chơi chế tạo tàu lượn bằng gỗ balsa điều khiển từ xa.", ["model aviation"], ["scale aeromodelling", "remote aeromodelling"], "Aeroplane scale modelling"),
    ],
    "Weather, Seasons & Natural Disasters": [
        ("flash-flood", "/ˌflæʃ ˈflʌd/", "n", "trận lũ quét cục bộ ập đến bất ngờ", "a sudden local flood of great volume and short duration following torrential rainfall", "Park rangers warned canyon hikers about deadly flash-floods after afternoon rainstorms.", "Các kiểm lâm viên đã cảnh báo những người đi bộ trong hẻm núi về những trận lũ quét chết người sau cơn mưa rào buổi chiều.", ["sudden inundation", "torrential surge"], ["dangerous flash-flood", "flash-flood warning"], "Flooding in a flash"),
        ("storm-surge", "/ˈstɔːrm sɜːrdʒ/", "n", "nước dâng do bão đánh sập đê biển", "a rising of the sea as a result of atmospheric pressure changes and wind associated with a storm", "The category five hurricane drove a twelve-foot storm-surge across coastal barrier islands.", "Cơn bão cấp 5 đã đẩy mực nước biển dâng do bão cao tới 3,6 mét quét qua các đảo chắn ven bờ.", ["tidal surge", "sea inundation"], ["deadly storm-surge", "massive storm-surge"], "Storm surging the ocean onshore"),
        ("heat-exhaustion", "/ˈhiːt ɪɡˌzɔːstʃən/", "n", "chứng kiệt sức vì sốc nhiệt độ cao", "a condition whose symptoms include heavy sweating and a rapid pulse, a result of the body overheating", "Marathon medics treated collapsed runners for severe heat-exhaustion during the sweltering race.", "Các nhân viên y tế tại giải chạy marathon đã sơ cứu cho những vận động viên bị kiệt sức nghiêm trọng vì sốc nhiệt trong thời tiết oi ả.", ["hyperthermia", "heat prostration"], ["suffer heat-exhaustion", "treat heat-exhaustion"], "Exhaustion caused by extreme heat"),
        ("blizzard-conditions", "/ˈblɪzərd kənˌdɪʃənz/", "n", "điều kiện bão tuyết mù mịt tầm nhìn gần bằng không", "weather conditions characterized by high winds, subfreezing temperatures, and zero visibility", "Highway patrols closed mountain passes as heavy blizzard-conditions blanketed the interstate.", "Lực lượng tuần tra đường cao tốc đã phong tỏa các con đèo trên núi khi điều kiện bão tuyết mù mịt bao phủ tuyến đường liên bang.", ["whiteout conditions"], ["severe blizzard-conditions"], "Conditions of a blinding blizzard"),
    ],
    "Philosophy, Psychology & Mindfulness": [
        ("absurdism", "/æbˈsɜːrdɪzəm/", "n", "chủ nghĩa phi lý (triết học Albert Camus)", "the belief that a search for meaning is inherently in conflict with the actual lack of meaning, but that one should accept this", "Albert Camus articulated absurdism in 'The Myth of Sisyphus', urging defiance against absurdity.", "Albert Camus đã luận giải chủ nghĩa phi lý trong tác phẩm 'Huyền thoại Sisyphus', kêu gọi sự phản kháng lại sự vô nghĩa của cuộc đời.", ["existential rebellion"], ["philosophy of absurdism", "Camusian absurdism"], "Absurd conflict between human need for meaning and silent cosmos"),
        ("moral-relativism", "/ˌmɒrəl ˈrɛlətɪvɪzəm/", "n", "thuyết tương đối về đạo đức", "the view that moral judgments are true or false only relative to some particular standpoint and that no standpoint is uniquely privileged", "Anthropologists debate whether universal human rights can reconcile with cultural moral-relativism.", "Các nhà nhân học tranh luận liệu nhân quyền phổ quát có thể hòa giải được với thuyết tương đối về đạo đức văn hóa hay không.", ["ethical subjectivism"], ["ethical moral-relativism"], "Morals relative to cultures"),
        ("solipsistic", "/ˌsɒlɪpˈsɪstɪk/", "adj", "mang tính duy ngã, chỉ tin bản thân tồn tại", "characterized by the belief that only one's own self exists or can be proved to exist", "Critics accused the avant-garde novelist of writing insufferably solipsistic auto-fiction.", "Các nhà phê bình cáo buộc tiểu thuyết gia tiên phong đã viết những cuốn tiểu thuyết tự truyện mang tính duy ngã khó chịu.", ["egocentric", "self-absorbed"], ["solipsistic worldview", "solipsistic prose"], "Solus (alone) + ipse (self)"),
        ("altruistic-tendency", "/ˌæltruˈɪstɪk ˈtɛndənsi/", "n", "khuynh hướng vị tha sống vì cộng đồng", "an inclination to show selfless concern for the welfare of others", "Developmental psychologists study the emergence of natural altruistic-tendency in young toddlers.", "Các nhà tâm lý học phát triển nghiên cứu sự xuất hiện của khuynh hướng vị tha tự nhiên ở trẻ mới biết đi.", ["benevolent disposition"], ["innate altruistic-tendency"], "Tendency to serve others"),
        ("epistemological-doubt", "/ɪˌpɪstɪməˈlɒdʒɪkəl daʊt/", "n", "sự hoài nghi nhận thức luận (hoài nghi Cartesian)", "philosophical skepticism questioning the foundation and validity of what human beings claim to know", "Descartes used systematic epistemological-doubt to discover his indubitable 'Cogito, ergo sum'.", "Descartes đã sử dụng phương pháp hoài nghi nhận thức luận có hệ thống để tìm ra chân lý không thể bác bỏ: 'Tôi tư duy, nên tôi tồn tại'.", ["Cartesian skepticism"], ["systematic epistemological-doubt"], "Doubting knowing itself"),
        ("stoic-mindset", "/ˈstoʊɪk ˈmaɪndˌsɛt/", "n", "tư duy khắc kỷ điềm tĩnh trước sóng gió", "a mental attitude focusing on accepting what cannot be controlled while mastering one's own responses", "Developing a resilient stoic-mindset shields entrepreneurs from emotional burnout in volatility.", "Việc rèn luyện một tư duy khắc kỷ kiên cường giúp các doanh nhân tránh khỏi tình trạng kiệt quệ cảm xúc trước những biến động.", ["unshakeable composure"], ["adopt a stoic-mindset"], "Mindset of a Stoic philosopher"),
    ],
    "Animals, Wildlife & Marine Biology": [
        ("amphibian", "/æmˈfɪbiən/", "n", "loài động vật lưỡng cư (ếch, nhái, kỳ giông)", "a cold-blooded vertebrate animal of a class that comprises the frogs, toads, newts, and salamanders", "Amphibians are sensitive bio-indicators whose porous skins absorb water pollutants directly.", "Các loài lưỡng cư là những sinh vật chỉ thị sinh học nhạy cảm mà làn da xốp của chúng hấp thụ trực tiếp các chất ô nhiễm trong nước.", ["dual-life vertebrate"], ["amphibian population", "declining amphibians"], "Amphi (both) + bios (life in water and land)"),
        ("herbivore", "/ˈhɜːrbɪvɔːr/", "n", "động vật ăn cỏ", "an animal that feeds predominantly on plants and vegetation", "The African savanna supports vast migratory herds of grazing mammalian herbivores.", "Thảo nguyên châu Phi là nơi sinh sống của các đàn động vật có vú ăn cỏ di cư khổng lồ.", ["plant-eater", "vegetarian animal"], ["grazing herbivore", "mammalian herbivore"], "Herba (plant) + vorare (devour)"),
        ("echinoderm", "/ɪˈkaɪnoʊˌdɜːrm/", "n", "loài động vật da gai (sao biển, cầu gai)", "a marine invertebrate of the phylum such as starfishes, sea urchins, and sea cucumbers", "Echinoderms display five-fold radial symmetry and a specialized hydraulic water-vascular system.", "Các loài động vật da gai thể hiện sự đối xứng tỏa tròn năm cạnh và một hệ thống mạch nước thủy lực chuyên biệt.", ["spiny-skinned creature"], ["marine echinoderm", "study echinoderms"], "Echinos (hedgehog/spine) + derma (skin)"),
        ("detritivore", "/dɪˈtraɪtɪvɔːr/", "n", "sinh vật ăn mùn bã hữu cơ phân hủy", "an animal which feeds on dead organic material, especially plant detritus like earthworms", "Earthworms act as essential soil detritivores, cycling decaying leaves into rich humus.", "Giun đất đóng vai trò như những sinh vật ăn mùn bã thiết yếu trong đất, chuyển hóa lá cây mục nát thành lớp mùn giàu dinh dưỡng.", ["decomposer", "scavenger"], ["soil detritivore", "aquatic detritivore"], "Detritus (decaying debris) + vorare"),
        ("sessile", "/ˈsɛsaɪl/", "adj", "sống cố định bám đáy (sinh vật biển)", "fixed in one place; immobile, such as barnacles and mature coral polyps", "Adult barnacles live a sessile existence anchored permanently to wave-swept rocky shores.", "Hà biển trưởng thành có lối sống bám cố định một chỗ, bám chặt vĩnh viễn vào các bờ đá bị sóng đánh.", ["immobile", "anchored", "sedentary"], ["sessile organism", "sessile marine life"], "Sedere = to sit immobile"),
        ("endangered-species", "/ɪnˈdeɪndʒərd ˈspiːʃiːz/", "n", "các loài động vật có nguy cơ tuyệt chủng", "species of animal or plant that are seriously at risk of biological extinction", "The international treaty protects endangered-species from commercial poaching and black-market trafficking.", "Hiệp ước quốc tế bảo vệ các loài động vật có nguy cơ tuyệt chủng khỏi nạn săn trộm thương mại và buôn bán trái phép trên thị trường đen.", ["threatened wildlife"], ["protect endangered-species", "critically endangered-species"], "Species in danger of dying out"),
        ("predation", "/prɪˈdeɪʃən/", "n", "mối quan hệ săn mồi sinh học", "the preying of one animal on others in natural ecosystems", "The reintroduction of wolves restored natural predation balances across Yellowstone National Park.", "Việc tái thả chó sói đã khôi phục sự cân bằng săn mồi tự nhiên trên khắp Công viên Quốc gia Yellowstone.", ["predatory hunting", "carnivory"], ["natural predation", "predation pressure"], "Praedari = to rob/plunder prey"),
    ],
    "Innovation, Startups & Entrepreneurship": [
        ("growth-hacking", "/ˈɡroʊθ ˌhækɪŋ/", "n", "kỹ thuật tăng trưởng đột phá chi phí thấp", "a process of rapid experimentation across marketing funnels and product development to identify growth loops", "Dropbox used viral referral growth-hacking by awarding free cloud storage for friend invites.", "Dropbox đã sử dụng kỹ thuật tăng trưởng đột phá bằng việc tặng dung lượng lưu trữ đám mây miễn phí cho các lượt mời bạn bè.", ["rapid growth tactics"], ["clever growth-hacking", "growth-hacking strategy"], "Hacking fast user growth"),
        ("early-adopter", "/ˌɜːrli əˈdɒptər/", "n", "người tiên phong trải nghiệm công nghệ mới", "a person who starts using a new product or technology as soon as it becomes available", "Tech-savvy early-adopters provided critical initial telemetry before the public software launch.", "Những người tiên phong sành công nghệ đã cung cấp các dữ liệu từ xa ban đầu thiết yếu trước khi phần mềm ra mắt công chúng.", ["innovator", "pioneer user"], ["attract early-adopters", "early-adopter community"], "Adopting before mainstream"),
        ("seed-capital", "/ˈsiːd ˌkæpɪtl/", "n", "nguồn vốn hạt giống giai đoạn thành lập", "the initial money used when starting a business to prove a concept and build an MVP", "The university startup competition awarded fifty thousand dollars in non-dilutive seed-capital.", "Cuộc thi khởi nghiệp của trường đại học đã trao tặng 50.000 đô la tiền vốn hạt giống không làm loãng cổ phần.", ["initial funding", "startup capital"], ["raise seed-capital", "secure seed-capital"], "Capital to plant the venture seed"),
        ("venture-capitalist", "/ˈvɛntʃər ˌkæpɪtəlɪst/", "n", "nhà đầu tư mạo hiểm tổ chức", "an investor who provides capital to startup ventures exhibiting high growth potential in exchange for equity", "Prominent Silicon Valley venture-capitalists competed vigorously to lead the AI platform's Series B round.", "Các nhà đầu tư mạo hiểm nổi tiếng ở Thung lũng Silicon đã cạnh tranh quyết liệt để dẫn đầu vòng gọi vốn Series B của nền tảng AI.", ["VC", "institutional investor"], ["pitch to a venture-capitalist", "prominent venture-capitalist"], "Capitalist financing risky ventures"),
        ("liquidity-event", "/lɪˈkwɪdəti ɪˌvɛnt/", "n", "sự kiện thanh khoản cổ phần (IPO hoặc thâu tóm)", "an acquisition, merger, or IPO that allows early founders and investors to cash out equity", "An imminent stock exchange IPO represents a massive liquidity-event for early venture backers.", "Một đợt phát hành cổ phiếu ra công chúng sắp diễn ra đại diện cho một sự kiện thanh khoản khổng lồ cho các nhà đầu tư mạo hiểm ban đầu.", ["exit event", "IPO exit"], ["achieve a liquidity-event", "founder liquidity-event"], "Event turning equity paper into liquid cash"),
    ],
    "Software Engineering & Full-Stack Development": [
        ("continuous-delivery", "/kənˌtɪnjuəs dɪˈlɪvəri/", "n", "phát hành liên tục (tự động hóa đẩy code ra staging/prod)", "a software engineering approach in which teams produce software in short cycles, ensuring releases can happen reliably at any time", "Implementing continuous-delivery reduced average time-to-market for new features down to hours.", "Việc triển khai quy trình phát hành liên tục đã rút ngắn thời gian đưa tính năng mới ra thị trường xuống chỉ còn vài giờ.", ["automated release pipeline"], ["CI/CD", "continuous-delivery pipeline"], "Delivering code continuously to production"),
        ("distributed-system", "/dɪˈstrɪbjuːtɪd ˌsɪstəm/", "n", "hệ thống phân tán nhiều nút máy chủ", "a computing environment in which various components are spread across multiple computers on a network", "Engineers design distributed-systems with Byzantine fault tolerance to withstand node crashes.", "Các kỹ sư thiết kế các hệ thống phân tán với khả năng chịu lỗi Byzantine để chống chọi với tình trạng máy chủ thành phần bị sập.", ["cluster computing"], ["scale a distributed-system", "resilient distributed-system"], "System distributed across machines"),
        ("serverless-computing", "/ˈsɜːrvərləs kəmˌpjuːtɪŋ/", "n", "điện toán phi máy chủ (FaaS thực thi theo sự kiện)", "a cloud-computing execution model where the cloud provider dynamically manages the allocation of machine resources", "Startups save cloud hosting expenses by running event-triggered Lambdas via serverless-computing.", "Các công ty khởi nghiệp tiết kiệm chi phí lưu trữ đám mây bằng cách chạy các hàm Lambda kích hoạt theo sự kiện thông qua điện toán phi máy chủ.", ["FaaS", "event-driven architecture"], ["adopt serverless-computing", "serverless-computing architecture"], "Computing without managing physical servers"),
        ("stateless-architecture", "/ˈsteɪtləs ˌɑːrkɪtɛktʃər/", "n", "kiến trúc phi trạng thái (không lưu session trên server)", "a software design where the server does not store any state about the client session on the server", "A stateless-architecture allows reverse proxies to distribute incoming requests across any backend instance.", "Một kiến trúc phi trạng thái cho phép các máy chủ proxy ngược phân phối các yêu cầu đến bất kỳ phiên bản backend nào.", ["stateless design"], ["build stateless-architecture", "RESTful stateless-architecture"], "Architecture without session state"),
        ("monolithic-architecture", "/ˌmɒnəˈlɪθɪk ˌɑːrkɪtɛktʃər/", "n", "kiến trúc khối nguyên khối truyền thống", "a unified model for software where the user interface and data access code are combined into a single program", "Early stage projects often benefit from the rapid prototyping speed of a monolithic-architecture.", "Các dự án giai đoạn đầu thường hưởng lợi từ tốc độ tạo mẫu nhanh của một kiến trúc khối nguyên khối.", ["single-tier architecture"], ["legacy monolithic-architecture", "monolith to microservices"], "Single giant stone monolith architecture"),
        ("declarative-programming", "/dɪˈklærətɪv ˈproʊɡræmɪŋ/", "n", "lập trình khai báo (nêu rõ kết quả mong muốn)", "a programming paradigm that expresses the logic of a computation without describing its explicit control flow", "SQL and React JSX are classic examples of expressive declarative-programming paradigms.", "SQL và cú pháp React JSX là những ví dụ kinh điển về các mô hình lập trình khai báo giàu tính biểu đạt.", ["intent-based programming"], ["declarative-programming style"], "Declaring what you want, not how to loop"),
        ("imperative-programming", "/ɪmˈpɛrətɪv ˈproʊɡræmɪŋ/", "n", "lập trình mệnh lệnh (mô tả từng bước thực hiện)", "a programming paradigm that uses statements that change a program's state, detailing step-by-step algorithms", "C and assembly illustrate low-level imperative-programming where developers manually manipulate memory registers.", "C và hợp ngữ minh họa cho lập trình mệnh lệnh cấp thấp, nơi các nhà phát triển điều khiển trực tiếp từng thanh ghi bộ nhớ.", ["step-by-step programming"], ["imperative-programming paradigm"], "Giving explicit commands to processor"),
    ],
    "Machine Learning, Deep Learning & LLMs": [
        ("activation-function", "/ˌæktɪˈveɪʃən ˌfʌŋkʃən/", "n", "hàm kích hoạt nơ-ron (phi tuyến tính hóa mạng)", "a mathematical equation that determines the output of a neural network node given an input or set of inputs", "ReLU is the most popular non-linear activation-function due to its computational efficiency.", "ReLU là hàm kích hoạt phi tuyến tính phổ biến nhất hiện nay nhờ vào hiệu quả tính toán nhanh chóng.", ["non-linear gate"], ["ReLU activation-function", "sigmoid activation-function"], "Function determining neuron firing activation"),
        ("convolutional-neural-network", "/ˌkɒnvəˈluːʃənl ˈnjʊərəl ˈnɛtwɜːrk/", "n", "mạng nơ-ron tích chập xử lý thị giác máy tính", "a class of deep neural networks, most commonly applied to analyzing visual imagery", "Autonomous vehicles deploy real-time convolutional-neural-networks to classify pedestrians and road signs.", "Xe tự hành triển khai các mạng nơ-ron tích chập thời gian thực để phân loại người đi bộ và biển báo giao thông.", ["CNN", "ConvNet"], ["train a convolutional-neural-network"], "Convolving kernels over image matrices"),
        ("recurrent-neural-network", "/rɪˈkɜːrənt ˈnjʊərəl ˈnɛtwɜːrk/", "n", "mạng nơ-ron hồi quy xử lý chuỗi tuần tự", "a class of artificial neural networks where connections between nodes can create a cycle, allowing output from some nodes to affect subsequent input", "Before transformers, recurrent-neural-networks like LSTMs powered state-of-the-art machine translation engines.", "Trước khi có transformer, các mạng nơ-ron hồi quy như LSTM đã từng là cốt lõi của các cỗ máy dịch thuật hàng đầu.", ["RNN", "LSTM network"], ["sequence processing with recurrent-neural-network"], "Recurrent recurring loop connections"),
        ("generative-adversarial-network", "/ˈdʒɛnərətɪv ˌædvərˈsɛəriəl ˈnɛtwɜːrk/", "n", "mạng đối nghịch tạo sinh (bộ sinh và bộ phân biệt)", "a machine learning model where two neural networks compete against each other in a game", "Generative-adversarial-networks revolutionized photorealistic synthetic face generation.", "Mạng đối nghịch tạo sinh đã tạo ra cuộc cách mạng trong việc tạo ra những khuôn mặt tổng hợp sống động như thật.", ["GAN"], ["train a generative-adversarial-network"], "Generator vs Discriminator adversary game"),
        ("autoencoder", "/ˌɔːtoʊɛnˈkoʊdər/", "n", "mạng tự mã hóa nén và tái tạo đặc trưng dữ liệu", "a type of artificial neural network used to learn efficient data codings in an unsupervised manner", "Denoising autoencoders compress noisy input images into compact bottleneck latent features.", "Các bộ tự mã hóa khử nhiễu nén những hình ảnh đầu vào nhiều tạp âm thành các đặc trưng tiềm ẩn nút thắt cổ chai nhỏ gọn.", ["neural compressor"], ["variational autoencoder", "train an autoencoder"], "Encoding itself into compressed latent code"),
        ("gradient-clipping", "/ˈɡreɪdiənt ˈklɪpɪŋ/", "n", "cắt gọt gradient (chống bùng nổ gradient khi train)", "a technique to prevent exploding gradients in very deep neural networks by capping gradient values", "Applying gradient-clipping during backpropagation stabilized large language model training.", "Áp dụng kỹ thuật cắt gọt gradient trong quá trình lan truyền ngược đã giúp ổn định việc huấn luyện các mô hình ngôn ngữ lớn.", ["gradient thresholding"], ["apply gradient-clipping", "gradient-clipping threshold"], "Clipping gradients when they exceed limits"),
        ("batch-normalization", "/ˈbætʃ ˌnɔːrməlaɪˈzeɪʃən/", "n", "chuẩn hóa theo lô mini trong mạng sâu", "a method used to make training of artificial neural networks faster and more stable through normalization of the layers' inputs", "Batch-normalization accelerates deep convolutional network convergence by mitigating internal covariate shift.", "Chuẩn hóa theo lô giúp tăng tốc độ hội tụ của mạng tích chập sâu bằng cách giảm thiểu sự dịch chuyển biến đồng thời nội bộ.", ["BatchNorm"], ["insert batch-normalization layers"], "Normalizing inputs across training batch"),
        ("vanishing-gradient", "/ˈvænɪʃɪŋ ˌɡreɪdiənt/", "n", "hiện tượng triệt tiêu gradient (đạo hàm tiến dần về 0)", "a problem where the gradient of the loss function becomes exceedingly small as it is propagated backward", "Deep networks with sigmoid activations suffer from vanishing-gradients, preventing early layers from learning.", "Mạng nơ-ron sâu dùng hàm kích hoạt sigmoid mắc phải lỗi triệt tiêu gradient, khiến các tầng đầu tiên không thể học được.", ["gradient dissipation"], ["solve vanishing-gradient", "vanishing-gradient problem"], "Gradients vanishing into near zero"),
        ("prompt-engineering", "/ˈprɒmpt ˌɛndʒɪˈnɪərɪŋ/", "n", "kỹ thuật thiết kế câu lệnh tối ưu cho mô hình ngôn ngữ", "the practice of structuring text that can be interpreted and understood by a generative AI model", "Mastering prompt-engineering unlocks complex analytical reasoning and structured JSON outputs from LLMs.", "Làm chủ kỹ thuật thiết kế câu lệnh mở khóa khả năng lập luận phân tích phức tạp và định dạng đầu ra JSON chuẩn từ các mô hình LLM.", ["prompt crafting"], ["prompt-engineering techniques", "effective prompt-engineering"], "Engineering optimal prompts for AI"),
        ("vector-database", "/ˈvɛktər ˌdeɪtəbeɪs/", "n", "cơ sở dữ liệu vector lưu trữ embedding ngữ nghĩa", "a database that stores information as high-dimensional vectors, optimized for nearest-neighbor semantic search", "Pinecone and Milvus are leading vector-databases designed for ultra-fast document embedding indexing.", "Pinecone và Milvus là những cơ sở dữ liệu vector hàng đầu được thiết kế để lập chỉ mục embedding tài liệu siêu tốc.", ["semantic database", "similarity search engine"], ["query a vector-database", "vector-database indexing"], "Database built for vector embeddings"),
        ("multimodal-learning", "/ˌmʌltiˈmoʊdl ˈlɜːrnɪŋ/", "n", "học đa phương thức (kết hợp đồng thời chữ, ảnh, âm thanh)", "an area of artificial intelligence that can process and understand information from multiple modalities", "Modern frontier models leverage multimodal-learning to comprehend text, diagrams, audio, and video simultaneously.", "Các mô hình tiên tiến hiện đại tận dụng khả năng học đa phương thức để hiểu văn bản, biểu đồ, âm thanh và video cùng một lúc.", ["cross-modal AI"], ["multimodal-learning architecture"], "Learning across multiple sensory modes"),
        ("self-supervised-learning", "/ˌsɛlf ˈsuːpərvaɪzd ˈlɜːrnɪŋ/", "n", "học tự giám sát (tự tạo nhãn từ dữ liệu chưa gán nhãn)", "a form of machine learning where the system learns to predict masked parts of its input without human labels", "BERT relies on masked-token self-supervised-learning over terabytes of unannotated internet text.", "Mô hình BERT dựa vào phương pháp học tự giám sát che dấu token trên hàng terabyte văn bản mạng chưa được gán nhãn.", ["SSL", "unsupervised pretraining"], ["pretrain with self-supervised-learning"], "Supervising itself using intrinsic data masks"),
        ("pooling-layer", "/ˈpuːlɪŋ ˌleɪər/", "n", "tầng giảm mẫu gộp đặc trưng trong mạng CNN", "a layer in a neural network that reduces the spatial dimensions of the input representation", "Max pooling-layers downsample high-resolution feature maps to enhance rotational invariance.", "Các tầng gộp cực đại max-pooling giảm kích thước không gian của các bản đồ đặc trưng để tăng khả năng bất biến với phép quay.", ["downsampling layer"], ["max pooling-layer", "average pooling-layer"], "Pooling spatial pixels into summaries"),
        ("parameter-optimization", "/pəˈræmɪtər ˌɒptɪmaɪˈzeɪʃən/", "n", "tối ưu hóa tham số mạng nơ-ron", "the mathematical process of finding the optimal weights and biases that minimize the loss function", "Adam and RMSprop provide adaptive momentum during deep neural parameter-optimization.", "Các thuật toán Adam và RMSprop cung cấp động lượng thích ứng trong quá trình tối ưu hóa tham số mạng sâu.", ["weight optimization"], ["efficient parameter-optimization"], "Optimizing billions of model parameters"),
        ("learning-rate-decay", "/ˈlɜːrnɪŋ reɪt dɪˌkeɪ/", "n", "sự suy giảm tốc độ học theo thời gian huấn luyện", "a technique that decreases the step size during parameter updates as training progresses", "Cosine learning-rate-decay gradually cools optimization down to ensure stable model convergence.", "Kỹ thuật suy giảm tốc độ học theo hàm cosine giảm dần bước nhảy để đảm bảo mô hình hội tụ ổn định.", ["learning rate schedule"], ["apply learning-rate-decay", "cosine learning-rate-decay"], "Decaying learning rate to fine-tune steps"),
        ("cross-entropy", "/ˌkrɒs ˈɛntrəpi/", "n", "độ đo entropy chéo giữa hai phân phối xác suất", "a measure from the field of information theory, building upon entropy, used as a primary classification loss", "Categorical cross-entropy penalizes confident erroneous class predictions severely.", "Độ đo entropy chéo phân loại phạt rất nặng các dự đoán nhãn sai nhưng lại có độ tự tin cao.", ["classification loss metric"], ["calculate cross-entropy", "categorical cross-entropy"], "Cross entropy distance between distributions"),
    ],
}

# Now inspect current seen and filter EXTRA_WORDS
final_topup_part2 = {}
total_added = 0

for topic, words in EXTRA_WORDS.items():
    seen = get_current_seen(topic)
    clean_list = []
    for w_entry in words:
        w = w_entry[0].strip().lower()
        if w not in seen:
            seen.add(w)
            clean_list.append(w_entry)
            total_added += 1
    final_topup_part2[topic] = clean_list

# Load existing topup part 2 if exists
output_path = Path(__file__).parent / "data" / "topup_part2_topics_2_to_32.py"
existing_part2 = {}
try:
    import topup_part2_topics_2_to_32
    existing_part2 = getattr(topup_part2_topics_2_to_32, "TOPUP_PART2", {})
except Exception:
    pass

combined_part2 = {}
for t in set(list(existing_part2.keys()) + list(final_topup_part2.keys())):
    combined_part2[t] = []
    seen_in_t = set()
    if t in existing_part2:
        for item in existing_part2[t]:
            w = item[0].strip().lower()
            if w not in seen_in_t:
                seen_in_t.add(w)
                combined_part2[t].append(item)
    if t in final_topup_part2:
        for item in final_topup_part2[t]:
            w = item[0].strip().lower()
            if w not in seen_in_t:
                seen_in_t.add(w)
                combined_part2[t].append(item)

with open(output_path, "w", encoding="utf-8") as f:
    f.write("# -*- coding: utf-8 -*-\n")
    f.write('"""Top-up part 2 vocabulary bank for topics 2 to 32."""\n\n')
    f.write("TOPUP_PART2 = {\n")
    for topic, words in combined_part2.items():
        f.write(f'    "{topic}": [\n')
        for item in words:
            f.write(f"        {repr(item)},\n")
        f.write("    ],\n")
    f.write("}\n")

print(f"Updated {output_path} with {len(combined_part2)} topics, total entries: {sum(len(v) for v in combined_part2.values())}.")
