"""
scripts/build_topups_13_to_32.py
Generates authentic vocabulary top-ups for Topics 13 to 32.
"""

import json
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
OUT_FILE = BASE_DIR / "scripts" / "data" / "lexicon_topups_13_to_32.py"

TOPUPS = {
    "Emotions, Personality & Character": [
        ("amiable", "/ˈeɪ.mi.ə.bəl/", "adjective", "B2", "Thân thiện, dễ mến, hòa nhã", "Having or displaying a friendly and pleasant manner.", "She had an amiable personality that put nervous clients at ease.", "Cô ấy có tính cách hòa nhã giúp các khách hàng lo lắng cảm thấy an tâm.", ["friendly", "cordial"], ["amiable smile", "amiable demeanor"], "💡 Amicus (bạn bè) -> dễ kết bạn."),
        ("oblivious", "/əˈblɪv.i.əs/", "adjective", "B2", "Không hề hay biết, lơ đãng trước hoàn cảnh xung quanh", "Not aware of or not concerned about what is happening around one.", "He seemed completely oblivious to the rising tension in the conference room.", "Anh ta dường như hoàn toàn không hay biết về sự căng thẳng đang dâng cao trong phòng họp.", ["unaware", "heedless"], ["oblivious to", "remain oblivious"], "💡 Oblivion là sự quên lãng."),
        ("pragmatic", "/præɡˈmæt̬.ɪk/", "adjective", "B2", "Thực tế, coi trọng tính hiệu quả thực tế hơn lý thuyết", "Dealing with things sensibly and realistically in a practical way.", "A pragmatic executive evaluates strategies by measurable outcomes rather than hype.", "Một nhà điều hành thực tế đánh giá chiến lược bằng kết quả đo lường được thay vì lời đồn thổi.", ["practical", "down-to-earth"], ["pragmatic approach", "pragmatic solution"], "💡 Pragma là hành động thực tế."),
        ("eccentric", "/ɪkˈsen.trɪk/", "adjective", "B2", "Kỳ lạ, lập dị nhưng có nét độc đáo cuốn hút", "Unconventional and slightly strange.", "The eccentric professor was known for wearing mismatched socks to formal lectures.", "Vị giáo sư lập dị nổi tiếng với việc đi tất lệch màu tới các buổi thuyết giảng trang trọng.", ["quirky", "unconventional"], ["eccentric behavior", "eccentric genius"], "💡 Lệch khỏi tâm thông thường."),
        ("sullen", "/ˈsʌl.ən/", "adjective", "B2", "Ủ rũ, lầm lì, hờn dỗi không chịu giao tiếp", "Bad-tempered and sulky; gloomy.", "After receiving reprimands, he retreated into sullen silence at his desk.", "Sau khi bị khiển trách, anh ấy thu mình vào sự im lặng ủ rũ tại bàn làm việc.", ["morose", "glum"], ["sullen mood", "sullen silence"], "💡 Vẻ mặt bí xị, hờn dỗi."),
        ("complacent", "/kəmˈpleɪ.sənt/", "adjective", "C1", "Tự mãn, bằng lòng với thành tích mà mất cảnh giác", "Showing smug or uncritical satisfaction with oneself.", "Industry leaders risk losing market dominance if they become too complacent.", "Các công ty dẫn đầu ngành có nguy cơ mất thị phần thống lĩnh nếu trở nên quá tự mãn.", ["self-satisfied", "smug"], ["grow complacent", "dangerously complacent"], "💡 Bằng lòng quá sớm dẫn đến thụt lùi."),
        ("serene", "/səˈriːn/", "adjective", "B2", "Thanh thản, phẳng lặng, không gợn chút âu lo", "Calm, peaceful, and untroubled; tranquil.", "Her serene demeanor during the crisis helped stabilize team morale.", "Thần thái thanh thản của cô trong lúc khủng hoảng đã giúp ổn định tinh thần cả đội.", ["placid", "tranquil"], ["serene expression", "serene atmosphere"], "💡 Tâm tĩnh lặng như mặt hồ không sóng."),
        ("volatile", "/ˈvɑː.lə.t̬əl/", "adjective", "B2", "Dễ biến đổi đột ngột, tính khí thất thường bốc hỏa", "Liable to change rapidly and unpredictably, especially for the worse.", "Working with a volatile supervisor created chronic anxiety for team members.", "Làm việc với một quản lý tính khí thất thường gây ra nỗi lo lắng kéo dài cho các thành viên.", ["mercurial", "erratic"], ["volatile temper", "volatile mood"], "💡 Dễ bốc hơi, dễ phát nổ như chất khí."),
        ("facetious", "/fəˈsiː.ʃəs/", "adjective", "C1", "Bỡn cợt, đùa cợt không đúng lúc đúng chỗ", "Treating serious issues with deliberately inappropriate humor.", "His facetious remarks during the safety briefing were not appreciated by the inspector.", "Những lời nhận xét bỡn cợt của anh ta trong buổi phổ biến an toàn không được thanh tra chấp nhận.", ["flippant", "jocular"], ["facetious remark", "facetious comment"], "💡 Đùa nhạt lúc người khác đang nghiêm túc."),
        ("fastidious", "/fæsˈtɪd.i.əs/", "adjective", "C1", "Kỹ tính, cực kỳ chỉn chu và khắt khe về độ chính xác", "Very attentive to and concerned about accuracy and detail.", "She was fastidious about grammar and edited every article three times.", "Cô ấy cực kỳ kỹ tính về ngữ pháp và biên tập mọi bài viết tới ba lần.", ["meticulous", "scrupulous"], ["fastidious attention", "fastidious about"], "💡 Người ưa sự hoàn hảo đến từng chi tiết."),
        ("gregarious", "/ɡrɪˈɡer.i.əs/", "adjective", "B2", "Thích tụ tập, hòa đồng cởi mở với đám đông", "Fond of company; sociable.", "Extroverts are typically gregarious individuals who thrive in dynamic team environments.", "Người hướng ngoại thường là những cá nhân hòa đồng, phát triển mạnh trong môi trường nhóm năng động.", ["sociable", "outgoing"], ["gregarious personality", "naturally gregarious"], "💡 Sống chan hòa cùng bầy đàn (gregis)."),
        ("inquisitive", "/ɪnˈkwɪz.ə.t̬ɪv/", "adjective", "B2", "Ham học hỏi, tò mò thích khám phá tìm hiểu", "Curious or inquiring; eager to investigate and learn.", "An inquisitive mind is the most valuable asset for a scientific researcher.", "Một trí óc tò mò ham học hỏi là tài sản quý giá nhất của một nhà nghiên cứu khoa học.", ["curious", "inquiring"], ["inquisitive nature", "inquisitive child"], "💡 Luôn đặt câu hỏi (inquire)."),
        ("lucid", "/ˈluː.sɪd/", "adjective", "B2", "Minh mẫn, diễn đạt rõ ràng rành mạch", "Expressed clearly; easy to understand; showing clarity of thought.", "Despite advancing age, the retired scholar gave a lucid lecture on world history.", "Dù tuổi đã cao, học giả đã nghỉ hưu vẫn có bài thuyết giảng minh mẫn về lịch sử thế giới.", ["clear-headed", "articulate"], ["lucid explanation", "lucid moment"], "💡 Ánh sáng soi rọi sự minh triết."),
        ("stoic", "/ˈstoʊ.ɪk/", "adjective", "B2", "Kiên định, nhẫn nại cam chịu nghịch cảnh không than thở", "Enduring pain or hardship without showing one's feelings or complaining.", "The crew showed stoic courage as they weathered the intense Arctic blizzard.", "Thủy thủ đoàn thể hiện sự can đảm kiên định khi họ vượt qua trận bão tuyết Bắc Cực dữ dội.", ["uncomplaining", "enduring"], ["stoic resignation", "stoic attitude"], "💡 Triết học Khắc kỷ rèn luyện tâm không động."),
        ("tactful", "/ˈtækt.fəl/", "adjective", "B2", "Khéo léo tế nhị trong ứng xử và giao tiếp", "Having or showing tact; sensitive and thoughtful in interpersonal dealings.", "She delivered constructive criticism in a remarkably tactful manner.", "Cô ấy đưa ra lời phê bình mang tính xây dựng theo một cách ứng xử vô cùng khéo léo tế nhị.", ["diplomatic", "discreet"], ["tactful response", "tactful approach"], "💡 Ứng xử nhẹ nhàng không làm đau lòng người khác."),
        ("zealous", "/ˈzel.əs/", "adjective", "B2", "Hăng hái, nhiệt thành cống hiến hết mình", "Having or showing great energy or enthusiasm in pursuit of a cause.", "The young environmentalists were zealous advocates for plastic reduction campaigns.", "Những nhà môi trường trẻ tuổi là những người ủng hộ nhiệt thành cho các chiến dịch giảm thiểu rác thải nhựa.", ["enthusiastic", "fervent"], ["zealous supporter", "zealous commitment"], "💡 Đầy nhiệt huyết và lòng trung thành."),
        ("adamant", "/ˈæd.ə.mənt/", "adjective", "B2", "Cương quyết, quả quyết không lay chuyển", "Refusing to be persuaded or to change one's mind.", "Management was adamant that all safety protocols must be followed strictly.", "Ban lãnh đạo cương quyết rằng mọi quy trình an toàn đều phải được tuân thủ nghiêm ngặt.", ["resolute", "unyielding"], ["adamant about", "remain adamant"], "💡 Cứng rắn như kim cương (adamas)."),
        ("belligerent", "/bəˈlɪdʒ.ɚ.ənt/", "adjective", "C1", "Hiếu chiến, thô lỗ và sẵn sàng gây sự", "Hostile and aggressive; eager to initiate conflict.", "The customer became belligerent when denied an immediate refund without a receipt.", "Vị khách hàng trở nên hung hăng gây sự khi bị từ chối hoàn tiền ngay lập tức do thiếu hóa đơn.", ["aggressive", "combative"], ["belligerent tone", "belligerent demeanor"], "💡 Mang vũ khí chiến tranh (bellum gerere)."),
        ("capricious", "/kəˈprɪʃ.əs/", "adjective", "C1", "Thất thường, sáng nắng chiều mưa khó lường", "Given to sudden and unaccountable changes of mood or behavior.", "Investing based on the capricious whims of market sentiment is dangerous.", "Đầu tư dựa trên tâm lý thị trường thất thường sáng nắng chiều mưa là điều rất nguy hiểm.", ["fickle", "unpredictable"], ["capricious nature", "capricious decisions"], "💡 Đổi ý đột ngột không báo trước."),
        ("dogmatic", "/dɑːɡˈmæt̬.ɪk/", "adjective", "C1", "Giáo điều, khăng khăng bảo thủ ý kiến chủ quan", "Inclined to lay down principles as incontrovertibly true without evidence.", "A rigid and dogmatic mindset prevents professionals from adopting innovative tools.", "Tư duy cứng nhắc và giáo điều ngăn cản chuyên gia tiếp thu các công cụ đột phá.", ["opinionated", "inflexible"], ["dogmatic stance", "dogmatic assertion"], "💡 Áp đặt giáo điều thiếu kiểm chứng."),
        ("ebullient", "/ɪbˈʊl.i.ənt/", "adjective", "C1", "Sôi nổi, tràn trề năng lượng phấn khởi", "Cheerful and full of energy; exuberant.", "Her ebullient laughter reverberated across the festive banquet hall.", "Tiếng cười rộn rã sôi nổi của cô ấy vang vọng khắp sảnh tiệc lễ hội.", ["exuberant", "vivacious"], ["ebullient spirit", "ebullient mood"], "💡 Sôi trào nhiệt huyết như nước sôi sục."),
        ("forbearing", "/fɔːrˈber.ɪŋ/", "adjective", "C1", "Nhẫn nhịn, khoan dung độ lượng trước lỗi lầm người khác", "Patient and restrained, especially in the face of provocation.", "The senior mentor was remarkably forbearing with the interns' early mistakes.", "Người cố vấn kỳ cựu vô cùng nhẫn nhịn và bao dung trước những sai sót ban đầu của các thực tập sinh.", ["patient", "tolerant"], ["forbearing nature", "kind and forbearing"], "💡 Nhẫn nhịn chịu đựng với lòng từ bi."),
        ("garrulous", "/ˈɡer.ə.ləs/", "adjective", "C1", "Lắm lời, ba hoa nói liến thoắng về việc vụn vặt", "Excessively talkative, especially on trivial matters.", "The garrulous cab driver shared his entire life story during the twenty-minute ride.", "Người tài xế taxi lắm lời đã kể toàn bộ câu chuyện cuộc đời mình trong suốt chuyến đi hai mươi phút.", ["loquacious", "talkative"], ["garrulous passenger", "garrulous host"], "💡 Nói nhiều chuyện vụn vặt không dứt."),
        ("haughty", "/ˈhɑː.t̬i/", "adjective", "C1", "Kiêu kỳ, ngạo mạn khinh khỉnh coi thường người khác", "Arrogantly superior and disdainful.", "His haughty attitude alienated many talented teammates who refused to work with him.", "Thái độ kiêu căng ngạo mạn của anh ta đã làm mất lòng nhiều đồng đội tài năng, những người từ chối hợp tác cùng.", ["arrogant", "condescending"], ["haughty expression", "haughty disdain"], "💡 Vênh váo, mắt nhìn lên cao coi người khác thấp kém."),
        ("indolent", "/ˈɪn.dəl.ənt/", "adjective", "C1", "Lười biếng, chây lười trốn tránh công việc", "Wanting to avoid activity or exertion; lazy.", "The humid afternoon made the office staff feel unusually indolent and sluggish.", "Buổi chiều oi bức khiến nhân viên văn phòng cảm thấy uể oải và chây lười khác thường.", ["lazy", "slothful"], ["indolent habit", "indolent afternoon"], "💡 Không chịu vận động chân tay hay trí não."),
        ("judicious", "/dʒuːˈdɪʃ.əs/", "adjective", "C1", "Sáng suốt, khôn ngoan và thấu đáo trong phán đoán", "Having, showing, or done with good judgment or sense.", "The committee made a judicious investment that yielded substantial returns over decades.", "Hội đồng đã đưa ra một quyết định đầu tư sáng suốt mang lại lợi nhuận đáng kể qua nhiều thập kỷ.", ["prudent", "wise"], ["judicious choice", "judicious use of resources"], "💡 Phán đoán như một thẩm phán công tâm."),
        ("knavish", "/ˈneɪ.vɪʃ/", "adjective", "C2", "Bất lương, xảo quyệt đầy mưu mô đen tối", "Dishonest or unscrupulous; characteristic of a knave.", "The whistleblower exposed the executive's knavish scheme to inflate quarterly profits.", "Người thổi còi đã vạch trần âm mưu xảo quyệt bất lương của vị giám đốc nhằm thổi phồng lợi nhuận quý.", ["deceitful", "dishonorable"], ["knavish trick", "knavish conduct"], "💡 Kẻ tiểu nhân bất lương."),
        ("loquacious", "/loʊˈkweɪ.ʃəs/", "adjective", "C1", "Hoạt ngôn, ăn nói lưu loát lưu manh hoặc vui vẻ", "Tending to talk a great deal; talkative.", "After a glass of wine, he became delightfully loquacious and shared captivating anecdotes.", "Sau một ly rượu vang, ông ấy trở nên hoạt ngôn vui vẻ và chia sẻ những giai thoại cuốn hút.", ["talkative", "voluble"], ["loquacious host", "loquacious companion"], "💡 Gốc từ loqui (nói năng).")
    ],
    "Family, Relationships & Society": [
        ("matrimony", "/ˈmæt.rə.moʊ.ni/", "noun", "B2", "Hôn nhân, đời sống vợ chồng hợp pháp", "The state of being married; marriage.", "They entered holy matrimony in a cathedral surrounded by lifelong friends.", "Họ đã bước vào đời sống hôn thú thiêng liêng tại một thánh đường trước sự chứng kiến của bạn bè thân hữu.", ["marriage", "wedlock"], ["holy matrimony", "vows of matrimony"], "💡 Mater (mẹ) -> định chế tạo dựng thiên chức làm mẹ."),
        ("progeny", "/ˈprɑː.dʒə.ni/", "noun", "C1", "Con cháu, hậu duệ của một gia tộc", "A descendant or the descendants of a person, animal, or plant; offspring.", "The founder took pride in passing his values down to three generations of progeny.", "Người sáng lập tự hào khi truyền lại các giá trị đạo đức cho ba thế hệ con cháu nối dõi.", ["offspring", "descendants"], ["future progeny", "numerous progeny"], "💡 Hạt giống sinh sôi nảy nở nối tiếp."),
        ("ancestral", "/ænˈses.trəl/", "adjective", "B2", "Thuộc về tổ tiên truyền lại", "Inherited from or belonging to ancestors.", "The family gathered at their ancestral home to commemorate the spring equinox.", "Đại gia đình tụ họp tại ngôi nhà từ đường của tổ tiên để đón tiết xuân phân.", ["hereditary", "lineage-based"], ["ancestral home", "ancestral roots"], "💡 Di sản truyền đời từ ông bà tổ tiên."),
        ("lineage", "/ˈlɪn.i.ɪdʒ/", "noun", "B2", "Dòng dõi, huyết thống gia phả", "Linear descent from an ancestor; ancestry or pedigree.", "Historians traced the royal dynasty's lineage back to the thirteenth century.", "Các nhà sử học đã truy vết gia phả dòng dõi của vương triều hoàng gia từ tận thế kỷ thứ mười ba.", ["ancestry", "pedigree"], ["noble lineage", "direct lineage"], "💡 Đường kẻ (line) nối các thế hệ trong gia phả."),
        ("matriarch", "/ˈmeɪ.tri.ɑːrk/", "noun", "B2", "Nữ trưởng tộc, người bà đứng đầu gia đình", "A woman who is the head of a family or tribe.", "The respected matriarch governed family affairs with wisdom and quiet dignity.", "Người bà trưởng tộc đáng kính đã điều hành công việc gia đình bằng sự thông thái và vẻ tôn nghiêm trầm lặng.", ["female leader", "family head"], ["family matriarch", "revered matriarch"], "💡 Mater (mẹ) + arche (người đứng đầu)."),
        ("patriarch", "/ˈpeɪ.tri.ɑːrk/", "noun", "B2", "Tộc trưởng, người cha đứng đầu gia tộc", "The male head of a family or tribe.", "The elderly patriarch summoned all branches of the family for an important estate reading.", "Vị tộc trưởng cao tuổi triệu tập tất cả các nhánh trong gia tộc để công bố di chúc điền trang quan trọng.", ["family head", "chieftain"], ["venerable patriarch", "clan patriarch"], "💡 Pater (cha) + arche (người đứng đầu)."),
        ("monogamy", "/məˈnɑː.ɡə.mi/", "noun", "B2", "Chế độ một vợ một chồng chung thủy", "The practice or state of being married to one person at a time.", "Modern civil legislation enforces legal monogamy in marital contracts.", "Pháp luật dân sự hiện đại thực thi chế độ một vợ một chồng trong các hợp đồng hôn nhân.", ["single marriage", "fidelity"], ["practice monogamy", "strict monogamy"], "💡 Mono (một) + gamos (kết hôn)."),
        ("polygamy", "/pəˈlɪɡ.ə.mi/", "noun", "B2", "Chế độ đa thê hoặc đa phu", "The practice of having more than one wife or husband at the same time.", "Certain historical societies permitted polygamy among wealthy aristocratic clans.", "Một số xã hội trong lịch sử từng cho phép chế độ đa thê trong giới quý tộc giàu có.", ["plural marriage", "multiple spouses"], ["outlaw polygamy", "practice polygamy"], "💡 Poly (nhiều) + gamos (kết hôn)."),
        ("chaperone", "/ˈʃæp.ə.roʊn/", "noun", "B2", "Người đi kèm giám sát thanh thiếu niên", "A person who accompanies and looks after another person or group of people.", "Parents volunteered as chaperones during the overnight high school camping excursion.", "Các bậc phụ huynh đã tình nguyện làm người giám hộ đi kèm trong chuyến dã ngoại qua đêm của trường cấp ba.", ["escort", "guardian"], ["adult chaperone", "act as a chaperone"], "💡 Đi cùng để giữ gìn sự an toàn và nề nếp."),
        ("fraternity", "/frəˈtɝː.nə.t̬i/", "noun", "B2", "Tình anh em huynh đệ, hội nam sinh", "A group of people sharing a common profession or interest; brotherhood.", "Soldiers shared a lifelong bond of fraternity forged under harrowing wartime conditions.", "Những người lính chia sẻ mối liên kết tình huynh đệ cả đời được tôi luyện trong điều kiện thời chiến khốc liệt.", ["brotherhood", "camaraderie"], ["sense of fraternity", "college fraternity"], "💡 Frater (anh em trai) trong tiếng Latin."),
        ("sorority", "/səˈrɔːr.ə.t̬i/", "noun", "B2", "Hội nữ sinh, tình chị em gắn bó", "A society for female students in higher education.", "The university sorority organized philanthropic events to fund scholarships for underprivileged women.", "Hội nữ sinh đại học đã tổ chức các sự kiện từ thiện để gây quỹ học bổng cho phụ nữ có hoàn cảnh khó khăn.", ["sisterhood", "female club"], ["sorority sisters", "join a sorority"], "💡 Soror (chị em gái) trong tiếng Latin."),
        ("solidarity", "/ˌsɑː.ləˈder.ə.t̬i/", "noun", "B2", "Sự đoàn kết nhất trí vì mục tiêu chung", "Unity or agreement of feeling or action, especially among individuals with a common interest.", "Community members demonstrated immense solidarity in aiding flood victims.", "Các thành viên cộng đồng đã thể hiện tinh thần đoàn kết to lớn trong việc trợ giúp các nạn nhân vùng lũ.", ["unity", "cohesion"], ["show solidarity", "stand in solidarity"], "💡 Kết thành một khối rắn chắc (solid)."),
        ("assimilation", "/əˌsɪm.əˈleɪ.ʃən/", "noun", "C1", "Sự đồng hóa văn hóa hòa nhập xã hội", "The process of taking in and fully understanding information or absorbing into a culture.", "Cultural assimilation can be enriching but also poses risks to preserving indigenous dialects.", "Sự đồng hóa văn hóa có thể đem lại sự giao lưu phong phú nhưng cũng đặt ra rủi ro cho việc gìn giữ các thổ ngữ bản địa.", ["integration", "acculturation"], ["cultural assimilation", "process of assimilation"], "💡 Similis (giống nhau) -> biến đổi để hòa nhập vào số đông."),
        ("nepotism", "/ˈnep.ə.tɪ.zəm/", "noun", "B2", "Thói gia đình trị, bổ nhiệm nâng đỡ người thân quen", "The practice among those with power or influence of favoring relatives or friends.", "The company implemented strict anti-nepotism hiring guidelines to preserve workplace meritocracy.", "Công ty đã thực hiện các hướng dẫn tuyển dụng nghiêm ngặt chống gia đình trị để bảo vệ chế độ trọng dụng nhân tài.", ["favoritism", "bias"], ["charge of nepotism", "rampant nepotism"], "💡 Nepos (cháu trai) -> nâng đỡ cháu chắt người nhà.")
    ]
}

print(f"Loaded {len(TOPUPS)} topics for topups generation.")
