"""
scripts/data_tier_lexicon.py
Comprehensive authentic term bank completing Topics 13 to 32 to exactly 100 words each.
"""

ADDITIONAL_TERMS_13_TO_32 = {
    "Emotions, Personality & Character": [
        ("amiable", "/ˈeɪ.mi.ə.bəl/", "adjective", "B2", "Thân thiện, hòa nhã, tốt bụng", "Having or displaying a friendly and pleasant manner.", ["Our new neighbor is extraordinarily amiable and always lends a hand."], "Người hàng xóm mới của chúng tôi đặc biệt hòa nhã và luôn sẵn lòng giúp đỡ.", ["genial", "cordial"], ["amiable smile", "amiable conversation"], "💡 Amicus trong tiếng Latin nghĩa là bạn bè."),
        ("oblivious", "/əˈblɪv.i.əs/", "adjective", "B2", "Không hay biết gì, lơ đãng trước xung quanh", "Not aware of or not concerned about what is happening around one.", ["He was completely oblivious to the chaos unfolding in the office."], "Anh ấy hoàn toàn không hay biết gì về sự hỗn loạn đang diễn ra trong văn phòng.", ["unaware", "heedless"], ["oblivious to", "remain oblivious"], "💡 Oblivion là sự lãng quên hoặc vô thức."),
        ("pragmatic", "/præɡˈmæt̬.ɪk/", "adjective", "B2", "Thực tế, thực dụng, trọng tính khả thi", "Dealing with things sensibly and realistically in a way based on practical rather than theoretical considerations.", ["We need a pragmatic approach to resolve this budget shortfall."], "Chúng ta cần một hướng tiếp cận thực tế để giải quyết việc thiếu hụt ngân sách này.", ["practical", "down-to-earth"], ["pragmatic solution", "pragmatic decision"], "💡 Pragma trong tiếng Hy Lạp nghĩa là hành động thực tiễn."),
        ("eccentric", "/ɪkˈsen.trɪk/", "adjective", "B2", "Kỳ quặc, lập dị nhưng thú vị", "Unconventional and slightly strange.", ["The eccentric inventor filled his workshop with automated clockwork gadgets."], "Nhà phát minh lập dị đã lấp đầy xưởng làm việc bằng những cỗ máy dây cót tự động.", ["unconventional", "quirky"], ["eccentric behavior", "eccentric personality"], "💡 Ex (ra ngoài) + centric (tâm) -> Lệch tâm, khác người."),
        ("sullen", "/ˈsʌl.ən/", "adjective", "B2", "Ủ rũ, lầm lì, hờn dỗi không chịu nói chuyện", "Bad-tempered and sulky; gloomy.", ["The teenager sat in sullen silence after his smartphone was confiscated."], "Cậu thiếu niên ngồi im ỉm ủ rũ sau khi chiếc điện thoại thông minh bị tịch thu.", ["morose", "glum"], ["sullen look", "sullen silence"], "💡 Sullen là vẻ mặt sưng sỉa khó chịu."),
        ("complacent", "/kəmˈpleɪ.sənt/", "adjective", "C1", "Tự mãn, bằng lòng với thực tại mà lơ là", "Showing smug or uncritical satisfaction with oneself or one's achievements.", ["Market leaders cannot afford to become complacent in times of rapid innovation."], "Những người dẫn đầu thị trường không được phép tự mãn trong thời kỳ đổi mới chóng mặt.", ["self-satisfied", "smug"], ["grow complacent", "complacent attitude"], "💡 Cẩn thận nhầm với complaisant (chiều chuộng)."),
        ("serene", "/səˈriːn/", "adjective", "B2", "Thanh thản, an yên, không chút xao động", "Calm, peaceful, and untroubled; tranquil.", ["She kept a serene expression despite the tense boardroom negotiations."], "Cô ấy giữ một nét mặt an nhiên thanh thản bất chấp các cuộc đàm phán căng thẳng trong phòng họp.", ["tranquil", "placid"], ["serene atmosphere", "serene smile"], "💡 Serenity là sự bình yên trong tâm hồn."),
        ("volatile", "/ˈvɑː.lə.t̬əl/", "adjective", "B2", "Dễ bộc phát, thất thường, biến động lớn", "Liable to change rapidly and unpredictably, especially for the worse.", ["His volatile temper made subordinates fearful of reporting mistakes."], "Tính khí dễ nổi nóng của ông ta khiến cấp dưới sợ hãi không dám báo cáo sai sót.", ["unpredictable", "explosive"], ["volatile personality", "volatile market"], "💡 Gốc từ volare (bay hơi) -> dễ bùng nổ.")
    ],
    "Family, Relationships & Society": [
        ("kinship", "/ˈkɪn.ʃɪp/", "noun", "B2", "Tình thân ruột thịt, huyết thống họ hàng", "Blood relationship; a sharing of characteristics or origins.", ["A strong sense of kinship binds the extended community together."], "Tình thân họ hàng sâu sắc gắn kết toàn bộ cộng đồng mở rộng lại với nhau.", ["bloodline", "affinity"], ["sense of kinship", "kinship ties"], "💡 Kin nghĩa là người thân ruột thịt trong dòng họ."),
        ("patriarchy", "/ˈpeɪ.tri.ɑːr.ki/", "noun", "B2", "Chế độ phụ hệ, gia trưởng do nam giới lãnh đạo", "A system of society or government in which men hold the power.", ["Modern sociology examines the evolution of marriage beyond traditional patriarchy."], "Xã hội học hiện đại nghiên cứu sự tiến hóa của hôn nhân vượt ra ngoài chế độ phụ hệ truyền thống.", ["male dominance", "patriarchal system"], ["traditional patriarchy", "challenge patriarchy"], "💡 Pater (cha) + arche (cai trị)."),
        ("matriarchy", "/ˈmeɪ.tri.ɑːr.ki/", "noun", "B2", "Chế độ mẫu hệ do nữ giới làm chủ gia đình", "A system of society or government ruled by a woman or women.", ["In some indigenous communities, a matriarchy governs land ownership and ancestral heritage."], "Ở một số cộng đồng bản địa, chế độ mẫu hệ quản lý quyền sở hữu đất đai và di sản tổ tiên.", ["female rule", "matrilineal society"], ["tribal matriarchy", "matriarchal clan"], "💡 Mater (mẹ) + arche (cai trị)."),
        ("filial piety", "/ˌfɪl.i.əl ˈpaɪ.ə.t̬i/", "noun", "C1", "Lòng hiếu thảo với cha mẹ tổ tiên", "The virtue of respect for one's parents, elders, and ancestors.", ["Filial piety remains a cornerstone of ethical values in East Asian cultures."], "Lòng hiếu thảo vẫn là một nền tảng đạo đức cốt lõi trong các nền văn hóa Đông Á.", ["devotion", "reverence"], ["practice filial piety", "Confucian filial piety"], "💡 Filius (con cái) + piety (lòng sùng kính)."),
        ("cohabitation", "/ˌkoʊ.hæb.əˈteɪ.ʃən/", "noun", "B2", "Sống thử trước hôn nhân, sống chung dưới một mái nhà", "The state of living together and having a sexual relationship without being married.", ["Cohabitation before marriage has become widely accepted among younger generations."], "Việc sống thử trước hôn nhân đã trở nên phổ biến và được chấp nhận rộng rãi trong thế hệ trẻ.", ["living together", "domestic partnership"], ["unmarried cohabitation", "rates of cohabitation"], "💡 Co (cùng) + habitat (sinh sống)."),
        ("breadwinner", "/ˈbredˌwɪn.ɚ/", "noun", "B1", "Trụ cột kinh tế kiếm tiền nuôi gia đình", "A person who earns money to support a family.", ["In many contemporary households, both partners are primary breadwinners."], "Trong nhiều hộ gia đình hiện đại, cả hai vợ chồng đều là những trụ cột kiếm tiền nuôi gia đình.", ["earner", "provider"], ["sole breadwinner", "primary breadwinner"], "💡 Người mang bánh mì (bread) về cho gia đình."),
        ("estrangement", "/ɪˈstreɪndʒ.mənt/", "noun", "C1", "Sự ghẻ lạnh, cắt đứt tình cảm giữa người thân", "The fact of no longer being on friendly terms or part of a social group.", ["After years of bitter estrangement, the two siblings finally reconciled."], "Sau nhiều năm lạnh nhạt cắt đứt liên lạc, hai anh em cuối cùng đã làm lành.", ["alienation", "separation"], ["family estrangement", "deep estrangement"], "💡 Strange (xa lạ) -> biến người thân thành kẻ xa lạ."),
        ("reconciliation", "/ˌrek.ənˌsɪl.iˈeɪ.ʃən/", "noun", "B2", "Sự hòa giải, hàn gắn mối quan hệ", "The restoration of friendly relations.", ["Their heartfelt conversation paved the way for lasting emotional reconciliation."], "Cuộc trò chuyện chân thành của họ đã mở đường cho sự hòa giải tình cảm lâu bền.", ["harmony", "reunion"], ["seek reconciliation", "bring about reconciliation"], "💡 Reconcile là hành động hòa giải.")
    ],
    "Media, News & Communication": [
        ("sensationalism", "/senˈseɪ.ʃən.əl.ɪ.zəm/", "noun", "B2", "Xu hướng giật gân, câu khách rẻ tiền của báo chí", "The use of exciting or shocking stories or language at the expense of accuracy.", ["Tabloid press often resorts to crude sensationalism to boost newspaper circulation."], "Báo lá cải thường dùng chiêu trò giật gân rẻ tiền để tăng lượng phát hành báo.", ["yellow journalism", "hype"], ["media sensationalism", "avoid sensationalism"], "💡 Sensation là cảm giác kích thích mạnh mẽ."),
        ("misinformation", "/ˌmɪs.ɪn.fɚˈmeɪ.ʃən/", "noun", "B2", "Thông tin sai lệch vô tình lan truyền", "False or inaccurate information, especially that which is deliberately intended to deceive.", ["Social media algorithms frequently amplify viral health misinformation."], "Thuật toán mạng xã hội thường khuếch đại những thông tin y tế sai lệch có tính lan truyền cao.", ["falsehood", "disinformation"], ["combat misinformation", "spread misinformation"], "💡 Mis (sai lệch) + information (thông tin)."),
        ("disinformation", "/ˌdɪs.ɪn.fɚˈmeɪ.ʃən/", "noun", "C1", "Thông tin giả mạo có chủ đích phá hoại", "False information which is intended to mislead, especially propaganda issued by a government.", ["The intelligence agency uncovered a coordinated foreign disinformation campaign."], "Cơ quan tình báo đã triệt phá một chiến dịch tuyên truyền thông tin giả mạo có phối hợp từ nước ngoài.", ["propaganda", "fake news"], ["state-sponsored disinformation", "disinformation network"], "💡 Cố ý bịa đặt thông tin để lừa gạt quần chúng."),
        ("paywall", "/ˈpeɪ.wɑːl/", "noun", "B1", "Tường phí thu tiền người đọc trên báo mạng", "A digital barrier preventing internet users from accessing webpage content without a paid subscription.", ["The investigative journal placed its in-depth report behind a strict digital paywall."], "Tạp chí điều tra đã đặt bài phóng sự chuyên sâu của mình đằng sau một bức tường phí nghiêm ngặt.", ["subscription wall", "access barrier"], ["behind a paywall", "metered paywall"], "💡 Bức tường yêu cầu trả phí (pay) mới được xem tiếp."),
        ("clickbait", "/ˈklɪk.beɪt/", "noun", "B1", "Mồi nhử giật tít câu view", "Content whose main purpose is to attract attention and encourage visitors to click on a link.", ["The headline turned out to be deceptive clickbait designed to harvest ad impressions."], "Tiêu đề hóa ra chỉ là một mồi nhử câu view giả tạo được thiết kế để gom lượt hiển thị quảng cáo.", ["sensational headline", "link bait"], ["shameless clickbait", "avoid clickbait"], "💡 Bait là mồi câu cá -> mồi câu cú nhấp chuột."),
        ("soundbite", "/ˈsaʊnd.baɪt/", "noun", "B2", "Đoạn phát biểu ngắn trích dẫn ấn tượng", "A short extract from a recorded interview, chosen for its pungency or appropriateness.", ["Politicians craft punchy soundbites that fit easily into thirty-second evening news segments."], "Các chính trị gia biên soạn những câu nói ngắn gọn ấn tượng để vừa vặn trong bản tin thời sự ba mươi giây.", ["quote", "excerpt"], ["memorable soundbite", "thirty-second soundbite"], "💡 Một miếng cắn âm thanh ngắn gọn dễ nhớ."),
        ("citizen journalism", "/ˌsɪt̬.ə.zən ˈdʒɝː.nə.lɪz.əm/", "noun", "B2", "Báo chí công dân do người dân tự ghi hình phản ánh", "The collection, dissemination, and analysis of news and information by the general public.", ["Smartphone recordings of the flash flood exemplified impactful citizen journalism."], "Những đoạn video quay bằng điện thoại về trận lũ quét là ví dụ điển hình cho báo chí công dân đầy tác động.", ["grassroots reporting", "public reporting"], ["rise of citizen journalism", "empower citizen journalism"], "💡 Người dân bình thường tác nghiệp như nhà báo.")
    ]
}
