# -*- coding: utf-8 -*-
"""
Generator for Topup Part 4 (Topics 37-40):
37. Pharmacology, Biotechnology & Genetics (70 words)
38. Corporate Law, Intellectual Property & Litigation (85 words)
39. Investment Banking, Stocks & Capital Markets (75 words)
40. Aviation, Flight Operations & Aerospace (75 words)
"""

import os

RAW_DATA_37 = [
    ("recombinant-dna", "/rɪˌkɒmbɪnənt ˌdiː ɛn ˈeɪ/", "n", "DNA tái tổ hợp kết hợp từ nhiều nguồn", "DNA that has been formed artificially by combining constituents from different organisms", "Recombinant-DNA technology revolutionized diabetic care by synthesizing human insulin inside bacterial cultures.", "Công nghệ DNA tái tổ hợp đã cách mạng hóa việc điều trị bệnh tiểu đường bằng cách tổng hợp insulin người trong vi khuẩn.", ["synthetic DNA"], ["recombinant-DNA technology"], "Recombining DNA strands"),
    ("crispr-cas9", "/ˌkrɪspər kæs ˈnaɪn/", "n", "công nghệ chỉnh sửa gen chính xác cao CRISPR-Cas9", "a unique technology that enables geneticists and medical researchers to edit parts of the genome by removing or altering sections of DNA", "CRISPR-Cas9 gene editing successfully eradicated the mutated hemoglobin gene in sickle cell patients.", "Kỹ thuật chỉnh sửa gen CRISPR-Cas9 đã loại bỏ thành công gen hemoglobin đột biến ở các bệnh nhân hồng cầu hình liềm.", ["gene editing tool"], ["utilize CRISPR-Cas9"], "Clustered Regularly Interspaced Short Palindromic Repeats"),
    ("polymerase-chain-reaction", "/pəˈlɪməreɪs ˌtʃeɪn riˈækʃən/", "n", "phản ứng chuỗi trùng hợp khuếch đại DNA (PCR)", "a laboratory technique used to make multiple copies of a specific DNA region quickly and accurately", "Quantitative polymerase-chain-reaction detected minute quantities of viral RNA within two hours.", "Phản ứng chuỗi trùng hợp định lượng đã phát hiện lượng RNA virus siêu nhỏ chỉ trong 2 giờ.", ["PCR"], ["run polymerase-chain-reaction"], "Polymerase enzyme chaining reactions"),
    ("monoclonal-antibody", "/ˌmɒnəˈkloʊnəl ˈæntɪˌbɒdi/", "n", "kháng thể đơn dòng nhân bản từ một tế bào miễn dịch", "an antibody made by cloning a unique white blood cell, with monovalent affinity to bind to the same epitope", "Monoclonal-antibodies like rituximab selectively target malignant B-cells while sparing healthy tissues.", "Các kháng thể đơn dòng như rituximab nhắm mục tiêu có chọn lọc vào các tế bào lympho B ác tính.", ["targeted antibody"], ["therapeutic monoclonal-antibody"], "Mono (single) + clone (identical replica)"),
    ("bioinformatics", "/ˌbaɪoʊˌɪnfərˈmætɪks/", "n", "tin sinh học phân tích dữ liệu sinh học phân tử", "the science of collecting and analyzing complex biological data such as genetic codes using computers", "Bioinformatics algorithms compared millions of genetic variants across global cancer databases.", "Các thuật toán tin sinh học đã so sánh hàng triệu biến thể gen trên khắp các cơ sở dữ liệu ung thư toàn cầu.", ["computational biology"], ["field of bioinformatics"], "Biology + informatics"),
    ("pharmacokinetics", "/ˌfɑːrməkoʊkɪˈnɛtɪks/", "n", "dược động học khảo sát hấp thu chuyển hóa thải trừ thuốc (PK)", "the branch of pharmacology concerned with the movement of drugs within the body over time (ADME)", "Pharmacokinetics profiles determine whether a tablet should be dosed once daily or every six hours.", "Hồ sơ dược động học quyết định xem một viên thuốc nên được dùng một lần mỗi ngày hay mỗi 6 giờ.", ["PK profile"], ["clinical pharmacokinetics"], "Pharmakon (drug) + kinetikos (moving)"),
    ("pharmacodynamics", "/ˌfɑːrməkoʊdaɪˈnæmɪks/", "n", "dược lực học nghiên cứu tác động sinh hóa của thuốc (PD)", "the study of the biochemical and physiological effects of drugs on the body or microorganisms", "Pharmacodynamics studies how antibiotic binding to bacterial ribosomes halts protein synthesis.", "Dược lực học nghiên cứu cách thức kháng sinh liên kết với ribosome vi khuẩn để ngăn chặn quá trình tổng hợp protein.", ["PD mechanism"], ["pharmacodynamics response"], "Pharmakon (drug) + dynamis (power)"),
    ("bioequivalence", "/ˌbaɪoʊɪˈkwɪvələns/", "n", "tương đương sinh học giữa thuốc gốc và biệt dược", "the biochemical similarity of two drugs that share the same active ingredient and demonstrate equal bioavailability", "Regulatory agencies demand proof of bioequivalence before licensing generic pharmaceutical tablets.", "Các cơ quan quản lý yêu cầu bằng chứng về tương đương sinh học trước khi cấp phép cho các viên thuốc gốc generic.", ["comparable efficacy"], ["establish bioequivalence"], "Biological equivalence"),
    ("bioavailability", "/ˌbaɪoʊəˌveɪləˈbɪləti/", "n", "sinh khả dụng (tỷ lệ thuốc vào được tuần hoàn chung)", "the proportion of a drug or other substance which enters the circulation when introduced into the body", "Intravenous administration guarantees one hundred percent bioavailability, bypassing gut absorption.", "Đường tiêm tĩnh mạch đảm bảo sinh khả dụng 100%, bỏ qua quá trình hấp thu qua đường ruột.", ["systemic absorption"], ["high bioavailability"], "Available biologically"),
    ("therapeutic-index", "/ˌθɛrəˈpjuːtɪk ˈɪndɛks/", "n", "chỉ số điều trị đo khoảng cách giữa liều hiệu quả và liều độc", "a quantitative measurement of the relative safety of a drug, comparing toxic dose to effective dose", "Warfarin has a narrow therapeutic-index requiring frequent international normalized ratio blood tests.", "Warfarin có chỉ số điều trị hẹp đòi hỏi phải xét nghiệm máu kiểm tra chỉ số INR thường xuyên.", ["safety margin"], ["narrow therapeutic-index"], "Therapeutic window index"),
    ("mrna-vaccine", "/ˌɛm ɑːr ɛn ˈeɪ vækˈsiːn/", "n", "vắc-xin sử dụng công nghệ RNA thông tin", "a type of vaccine that uses a copy of a molecule called messenger RNA to produce an immune response", "The rapid development of the COVID-19 mRNA-vaccine marked a historic milestone in vaccinology.", "Sự phát triển nhanh chóng của vắc-xin mRNA phòng COVID-19 đã đánh dấu một cột mốc lịch sử trong ngành chế tạo vắc-xin.", ["messenger RNA vaccine"], ["administer an mRNA-vaccine"], "Messenger RNA vaccine"),
    ("flow-cytometry", "/floʊ saɪˈtɒmɪtri/", "n", "kỹ thuật đếm và phân tích tế bào dòng chảy", "a laser-based biophysical technology employed in cell counting, cell sorting, and biomarker detection", "Flow-cytometry quantified CD4 T-cell counts in blood samples within minutes.", "Kỹ thuật tế bào dòng chảy đã định lượng số lượng tế bào lympho T CD4 trong các mẫu máu trong vài phút.", ["cell sorting technology"], ["perform flow-cytometry"], "Flow + cyto (cell) + metry"),
    ("chimeric-antigen-receptor", "/kaɪˌmɪərɪk ˈæntɪdʒən rɪˈsɛptər/", "n", "thụ thể kháng nguyên dạng khảm (CAR)", "an engineered receptor graft onto immune effector cells to reprogram T-cells to target specific tumor antigens", "Chimeric-antigen-receptor T-cell therapy achieved remarkable remissions in relapsed leukemia.", "Liệu pháp tế bào T thụ thể kháng nguyên dạng khảm đã đạt được những đợt thuyên giảm đáng kinh ngạc ở bệnh bạch cầu tái phát.", ["CAR"], ["engineer chimeric-antigen-receptor"], "Chimera (hybrid creature) receptor"),
    ("plasmid-vector", "/ˈplæzmɪd ˌvɛktər/", "n", "vector plasmid mang gen chèn vào vi khuẩn", "a small circular double-stranded DNA molecule used as a vehicle to artificially carry foreign genetic material into another cell", "Scientists inserted the insulin gene into a bacterial plasmid-vector for industrial protein expression.", "Các nhà khoa học đã chèn gen insulin vào một vector plasmid vi khuẩn để biểu hiện protein quy mô công nghiệp.", ["cloning vector"], ["construct plasmid-vector"], "Circular plasmid vector carrier"),
    ("epigenetics", "/ˌɛpɪdʒɪˈnɛtɪks/", "n", "di truyền biểu sinh (thay đổi biểu hiện gen không đổi chuỗi DNA)", "the study of changes in organisms caused by modification of gene expression rather than alteration of the genetic code", "Epigenetics explains how environmental factors like stress and diet turn tumor suppressor genes on or off.", "Di truyền biểu sinh giải thích cách các yếu tố môi trường như căng thẳng và chế độ ăn bật hoặc tắt các gen ức chế khối u.", ["gene expression regulation"], ["epigenetics research"], "Epi (above) + genetics"),
    ("methylation", "/ˌmɛθɪˈleɪʃən/", "n", "sự methyl hóa DNA điều hòa hoạt tính của gen", "a biological process by which methyl groups are added to the DNA molecule, typically repressing gene transcription", "Aberrant promoter hypermethylation silenced tumor suppressor genes in colorectal cancer biopsies.", "Hiện tượng tăng methyl hóa vùng khởi động bất thường đã làm bất hoạt các gen ức chế khối u trong sinh thiết ung thư đại trực tràng.", ["DNA modification"], ["DNA methylation"], "Adding methyl CH3 chemical group"),
    ("transcription-factor", "/trænˈskrɪpʃən ˌfæktər/", "n", "yếu tố phiên mã điều hòa tốc độ sao chép mRNA", "a protein that controls the rate of transcription of genetic information from DNA to messenger RNA", "p53 is a vital transcription-factor that halts the cell cycle when critical DNA damage is detected.", "p53 là một yếu tố phiên mã quan trọng giúp ngăn chặn chu kỳ tế bào khi phát hiện tổn thương DNA nghiêm trọng.", ["gene regulator"], ["activate transcription-factor"], "Factor controlling DNA transcription"),
    ("rna-interference", "/ˌɑːr ɛn ˈeɪ ˌɪntərˈfɪərəns/", "n", "can thiệp RNA làm bất hoạt biểu hiện gen xấu", "a biological process in which RNA molecules inhibit gene expression or translation by neutralizing targeted mRNA", "Researchers employed rna-interference to selectively downregulate viral replication in infected cells.", "Các nhà nghiên cứu đã sử dụng kỹ thuật can thiệp RNA để làm giảm biểu hiện có chọn lọc sự sao chép của virus trong tế bào.", ["RNAi"], ["harness RNA-interference"], "RNA molecules interfering with translation"),
    ("enzyme-kinetics", "/ˈɛnzaɪm kɪˌnɛtɪks/", "n", "động học enzym nghiên cứu tốc độ phản ứng sinh hóa", "the study of the chemical reactions that are catalyzed by enzymes, measuring reaction rates and substrate affinities", "Michaelis-Menten equations provide the mathematical foundation for analyzing enzyme-kinetics in drug design.", "Các phương trình Michaelis-Menten cung cấp nền tảng toán học để phân tích động học enzym trong thiết kế thuốc.", ["catalytic rate analysis"], ["study enzyme-kinetics"], "Kinetic velocity of enzyme actions"),
    ("allosteric-regulation", "/ˌæloʊˈstɛrɪk ˌrɛɡjʊˈleɪʃən/", "n", "điều hòa dị lập thể qua vị trí liên kết phụ", "the regulation of an enzyme by binding an effector molecule at a site other than the enzyme's active site", "Allosteric-regulation allows drugs to fine-tune protein activity without completely blocking the substrate pocket.", "Điều hòa dị lập thể cho phép thuốc tinh chỉnh hoạt tính của protein mà không cần chặn hoàn toàn túi cơ chất chính.", ["non-competitive modulation"], ["undergo allosteric-regulation"], "Allos (other) + stereos (solid/place)"),
    ("receptor-agonist", "/rɪˈsɛptər ˌæɡənɪst/", "n", "chất chủ vận kích hoạt thụ thể sinh học", "a chemical that binds to a receptor and activates the receptor to produce a biological response", "Albuterol acts as a beta-2 adrenergic receptor-agonist dilating bronchial airways during asthma attacks.", "Albuterol hoạt động như một chất chủ vận thụ thể beta-2 adrenergic làm giãn phế quản trong các cơn hen suyễn.", ["receptor activator"], ["potent receptor-agonist"], "Agonistes = actor, activator"),
    ("receptor-antagonist", "/rɪˈsɛptər ænˌtæɡənɪst/", "n", "chất đối kháng phong bế thụ thể sinh học", "a biological receptor ligand that blocks or dampens a biological response by binding to and blocking a receptor", "Naloxone is an opioid receptor-antagonist that immediately reverses the lethal respiratory depression of heroin.", "Naloxone là một chất đối kháng thụ thể opioid có khả năng đảo ngược ngay lập tức tình trạng ức chế hô hấp gây tử vong do heroin.", ["receptor blocker"], ["competitive receptor-antagonist"], "Antagonistes = opponent, blocker"),
    ("half-life", "/ˈhæf laɪf/", "n", "thời gian bán thải của thuốc trong huyết tương (t1/2)", "the time taken for the plasma concentration of a drug to reduce by half in the body", "A drug with a twenty-four-hour elimination half-life allows convenient once-daily oral dosing.", "Một loại thuốc có thời gian bán thải 24 giờ cho phép chia liều uống một lần mỗi ngày rất thuận tiện.", ["elimination half-life"], ["terminal half-life"], "Time for half of substance to clear"),
    ("clearance-rate", "/ˈklɪərəns reɪt/", "n", "tốc độ thanh thải thuốc khỏi huyết tương", "the volume of plasma from which a substance is completely removed per unit of time by the kidneys or liver", "Decreased renal clearance-rate in elderly patients necessitates adjusting the daily antibiotic dosage downward.", "Tốc độ thanh thải qua thận giảm ở bệnh nhân cao tuổi đòi hỏi phải điều chỉnh giảm liều kháng sinh hàng ngày.", ["drug elimination velocity"], ["renal clearance-rate"], "Rate of clearing drug from blood"),
    ("volume-of-distribution", "/ˌvɒljuːm əv ˌdɪstrɪˈbjuːʃən/", "n", "thể tích phân bố biểu kiến của thuốc (Vd)", "the theoretical volume that would be necessary to contain the total amount of an administered drug at the same concentration as in blood", "Lipophilic anesthetics have a massive volume-of-distribution because they readily penetrate deep adipose tissues.", "Các thuốc gây mê ưa lipid có thể tích phân bố rất lớn vì chúng dễ dàng thâm nhập sâu vào các mô mỡ.", ["apparent distribution volume"], ["calculate volume-of-distribution"], "Apparent volume of drug dilution"),
    ("cytochrome-p450", "/ˌsaɪtəˌkroʊm ˌpiː fɔːr ˈfɪfti/", "n", "hệ enzym gan chuyển hóa phần lớn các loại thuốc (CYP450)", "a superfamily of enzymes containing heme that catalyze the oxidation of organic substances and drugs in the liver", "Grapefruit juice inhibits cytochrome-P450 3A4, causing potentially dangerous elevations in statin blood levels.", "Nước bưởi ức chế enzym cytochrome-P450 3A4, gây ra sự tăng nồng độ nguy hiểm của thuốc hạ mỡ máu statin.", ["CYP enzyme system"], ["metabolized by cytochrome-P450"], "Cytochrome pigment with 450nm absorbance"),
    ("adverse-drug-reaction", "/ˌædvɜːrs ˈdrʌɡ riˌækʃən/", "n", "phản ứng có hại của thuốc ngoài ý muốn (ADR)", "an injury caused by taking medication, encompassing unintended harm arising from normal therapeutic doses", "Hospitals maintain vigilant surveillance systems to report any suspected adverse-drug-reactions to regulators.", "Các bệnh viện duy trì hệ thống giám sát cảnh giác để báo cáo bất kỳ phản ứng có hại nghi ngờ nào của thuốc lên cơ quan quản lý.", ["ADR", "drug toxicity event"], ["report adverse-drug-reaction"], "Adverse unintended reaction to drug"),
    ("pharmacogenomics", "/ˌfɑːrməkoʊdʒɪˈnoʊmɪks/", "n", "dược lý học hệ gen cá thể hóa liều dùng theo gen", "the study of how genes affect a person's individual response to pharmacological drugs", "Pharmacogenomics screening identifies patients carrying HLA-B*1502 who risk toxic epidermal necrolysis from carbamazepine.", "Sàng lọc dược lý học hệ gen giúp xác định bệnh nhân mang alen HLA-B*1502 có nguy cơ bị hoại tử thượng bì do carbamazepine.", ["personalized drug genetics"], ["clinical pharmacogenomics"], "Pharmacology + genomics"),
    ("personalized-medicine", "/ˈpɜːrsənəlaɪzd ˈmɛdɪsɪn/", "n", "y học cá thể hóa điều trị theo đặc điểm từng bệnh nhân", "a medical model that customizes healthcare, with medical decisions and treatments tailored to the individual patient", "Targeting the specific EGFR mutation in a lung tumor is the hallmark of modern personalized-medicine.", "Nhắm vào đột biến EGFR cụ thể trong khối u phổi là dấu ấn tiêu biểu của nền y học cá thể hóa hiện đại.", ["precision medicine"], ["advance personalized-medicine"], "Medicine tailored to individual persons"),
    ("small-molecule-inhibitor", "/smɔːl ˈmɒlɪkjuːl ɪnˈhɪbɪtər/", "n", "thuốc phân tử nhỏ ức chế tín hiệu nội bào", "a low molecular weight organic compound that enters cells easily to inhibit specific biological target proteins", "Imatinib was the pioneering small-molecule-inhibitor targeting the BCR-ABL kinase in chronic myeloid leukemia.", "Imatinib là thuốc ức chế phân tử nhỏ tiên phong nhắm vào kinase BCR-ABL trong bệnh bạch cầu dòng tủy mạn tính.", ["chemical enzyme inhibitor"], ["synthesize small-molecule-inhibitor"], "Small molecular weight inhibitor"),
    ("biosimilar", "/ˌbaɪoʊˈsɪmɪlər/", "n", "thuốc sinh học tương tự sinh dược phẩm gốc", "a biological product that is highly similar to and has no clinically meaningful differences from an existing approved biologic", "The introduction of biosimilars reduced the astronomical annual cost of rheumatoid arthritis therapy by thirty percent.", "Sự ra đời của các thuốc sinh học tương tự đã giảm 30% chi phí điều trị đắt đỏ hàng năm của bệnh viêm khớp dạng thấp.", ["biologic generic equivalent"], ["prescribe a biosimilar"], "Biologically similar therapeutic drug"),
    ("mass-spectrometry", "/ˌmæs spɛkˈtrɒmɪtri/", "n", "khối phổ học định danh cấu trúc phân tử chính xác", "an analytical tool useful for measuring the mass-to-charge ratio of molecules to identify chemical compounds", "Proteomics relies on tandem mass-spectrometry to identify thousands of translated peptide sequences simultaneously.", "Nghiên cứu hệ protein dựa vào phép đo khối phổ liên hợp để xác định đồng thời hàng nghìn trình tự peptide.", ["mass spec analysis"], ["utilize mass-spectrometry"], "Measuring masses across spectrum"),
    ("gel-electrophoresis", "/ˌdʒɛl ɪˌlɛktroʊfəˈriːsɪs/", "n", "điện di trên gel phân tách phân tử theo kích thước", "a laboratory method used to separate mixtures of DNA, RNA, or proteins according to molecular size and electric charge", "Agarose gel-electrophoresis separated PCR amplicons, confirming the expected 500 base-pair band size under ultraviolet light.", "Điện di gel agarose đã tách các sản phẩm khuếch đại PCR, xác nhận vạch kích thước 500 cặp bazơ dưới ánh sáng cực tím.", ["molecular gel separation"], ["run gel-electrophoresis"], "Electrophoretic migration through gel"),
    ("western-blot", "/ˌwɛstərn ˈblɒt/", "n", "kỹ thuật thẩm tách Western định lượng protein đặc hiệu", "an analytical technique used in molecular biology to detect specific protein molecules from among a complex mixture", "The Western-blot assay detected high expression levels of HER2 protein on the breast carcinoma cell lysates.", "Xét nghiệm thẩm tách Western đã phát hiện mức độ biểu hiện cao của protein HER2 trên dịch ly giải tế bào ung thư vú.", ["protein immunoblotting"], ["perform a Western-blot"], "Named after Southern blot technique"),
    ("antisense-oligonucleotide", "/ˌæntiˈsɛns ˌɒlɪɡoʊˌnjuːkliətaɪd/", "n", "chuỗi oligonucleotide đối mã khóa quá trình dịch mã gen", "a short synthetic single-stranded string of nucleic acids that binds to RNA to alter or disrupt gene protein expression", "Spinraza is a breakthrough antisense-oligonucleotide that modifies survival motor neuron pre-mRNA in spinal muscular atrophy.", "Spinraza là thuốc oligonucleotide đối mã đột phá giúp biến đổi pre-mRNA ở bệnh teo cơ tủy sống.", ["ASO therapy"], ["synthetic antisense-oligonucleotide"], "Anti-sense complementary nucleotide chain"),
    ("viral-vector", "/ˈvaɪrəl ˈvɛktər/", "n", "vector virus vận chuyển gen lành vào tế bào đích", "a modified virus used as a vehicle to deliver genetic material into the nuclei of target host cells safely", "Adeno-associated viral-vectors are favored in gene therapy because they rarely trigger damaging host immune reactions.", "Các vector virus liên kết adeno rất được ưa chuộng trong liệu pháp gen vì chúng hiếm khi kích hoạt phản ứng miễn dịch gây hại.", ["gene delivery vehicle"], ["engineer a viral-vector"], "Virus functioning as delivery vector"),
    ("adeno-associated-virus", "/ˌædɪnoʊ əˌsoʊsieɪtɪd ˈvaɪrəs/", "n", "virus liên kết adeno không gây bệnh dùng trong liệu pháp gen (AAV)", "a small replication-defective virus commonly utilized as an engineered vector for human gene replacement therapy", "Scientists engineered an adeno-associated-virus capsid designed to cross the restrictive blood-brain barrier.", "Các nhà khoa học đã thiết kế một vỏ capsid virus liên kết adeno có khả năng vượt qua hàng rào máu não nghiêm ngặt.", ["AAV vector"], ["recombinant adeno-associated-virus"], "Adeno associated non-pathogenic virus"),
    ("car-t-cell", "/ˌkɑːr ˈtiː sɛl/", "n", "tế bào T mang thụ thể kháng nguyên dạng khảm đặc trị ung thư", "a patient's T-cell that has been genetically altered in a cleanroom laboratory to attack cancer cells aggressively", "Infusion of CAR-T-cells destroyed drug-resistant lymphoma lesions that had resisted multiple rounds of chemotherapy.", "Truyền tế bào CAR-T đã tiêu diệt các tổn thương u lympho kháng thuốc vốn đã không đáp ứng với nhiều đợt hóa trị.", ["engineered T lymphocyte"], ["autologous CAR-T-cell"], "Chimeric Antigen Receptor T-cell"),
    ("immunogenicity", "/ˌɪmjʊnoʊdʒəˈnɪsəti/", "n", "tính sinh miễn dịch (khả năng kích hoạt đáp ứng miễn dịch)", "the ability of a particular substance, such as an antigen or biological epitope, to provoke an immune response", "Low immunogenicity is essential for therapeutic proteins to avoid neutralizing anti-drug antibody production.", "Tính sinh miễn dịch thấp là điều kiện tiên quyết đối với protein điều trị để tránh tạo ra kháng thể kháng thuốc.", ["antigenic reactivity"], ["test for immunogenicity"], "Ability to generate immune response"),
    ("oncogene", "/ˈɒŋkoʊdʒiːn/", "n", "gen sinh ung thư thúc đẩy tế bào phân chia mất kiểm soát", "a gene which in certain circumstances can transform a normal cell into a hyper-proliferative tumor cell", "Mutations in the KRAS oncogene drive uncontrolled cellular proliferation in pancreatic ductal adenocarcinoma.", "Đột biến ở gen sinh ung thư KRAS dẫn đến sự phân chia tế bào mất kiểm soát trong ung thư biểu mô tuyến tụy.", ["cancer-causing gene"], ["activate an oncogene"], "Onkos (mass/tumor) + gene"),
    ("tumor-suppressor-gene", "/ˈtjuːmər səˌprɛsər ˈdʒiːn/", "n", "gen đè nén khối u bảo vệ tế bào khỏi đột biến ác tính", "a normal gene that slows down cell division, repairs DNA errors, and tells cells when to undergo programmed death", "Loss of both alleles of the BRCA1 tumor-suppressor-gene substantially elevates lifetime ovarian and breast cancer risk.", "Mất cả hai alen của gen đè nén khối u BRCA1 làm tăng đáng kể nguy cơ mắc ung thư buồng trứng và ung thư vú suốt đời.", ["anti-oncogene"], ["inactivate tumor-suppressor-gene"], "Gene suppressing tumor development"),
    ("apoptosis-pathway", "/ˌæpəpˈtoʊsɪs ˈpæθweɪ/", "n", "con đường tự chết theo chương trình của tế bào lỗi", "the programmed cell death sequence that multicellular organisms use to dispose of damaged or unwanted cells orderly", "Venetoclax binds BCL-2 to reactivate the intrinsic apoptosis-pathway, driving malignant leukemia cells to self-destruct.", "Venetoclax liên kết với BCL-2 để tái kích hoạt con đường tự chết theo chương trình nội tại, khiến tế bào bạch cầu ác tính tự hủy.", ["programmed cell death"], ["trigger apoptosis-pathway"], "Apo (away) + ptosis (falling)"),
    ("angiogenesis-inhibition", "/ˌændʒioʊˈdʒɛnɪsɪs ɪnhɪˈbɪʃən/", "n", "ức chế sinh mạch máu mới nuôi khối u", "the blocking of the growth of new blood vessels that tumors require to obtain nutrients and oxygen to grow", "Bevacizumab achieves angiogenesis-inhibition by binding circulating vascular endothelial growth factor (VEGF).", "Bevacizumab đạt hiệu quả ức chế sinh mạch máu bằng cách liên kết với yếu tố tăng trưởng nội mô mạch máu lưu hành.", ["blood vessel suppression"], ["anti-angiogenesis-inhibition"], "Angio (vessel) + genesis (creation)"),
    ("bioreactor", "/ˈbaɪoʊriːˌæktər/", "n", "bình phản ứng sinh học nuôi cấy tế bào sản xuất thuốc", "an apparatus in which a biological reaction or process is carried out, especially on an industrial scale for drug manufacturing", "A two-thousand-liter stainless-steel bioreactor cultured Chinese hamster ovary cells producing therapeutic antibodies.", "Bình phản ứng sinh học bằng thép không gỉ dung tích 2.000 lít nuôi cấy tế bào buồng trứng chuột đồng sản xuất kháng thể điều trị.", ["cell fermentation vessel"], ["industrial bioreactor"], "Biological reaction vessel"),
    ("downstream-processing", "/ˈdaʊnstriːm ˌprɒsɛsɪŋ/", "n", "quy trình tinh chế và tinh sạch sinh phẩm sau lên men", "the recovery and purification of biosynthetic products, particularly pharmaceuticals, from cell culture harvest", "Downstream-processing uses protein A affinity chromatography columns to separate antibodies from cell debris.", "Quy trình xử lý hạ nguồn sử dụng các cột sắc ký ái lực protein A để tách kháng thể khỏi các mảnh vỡ tế bào.", ["bioproduct purification"], ["optimize downstream-processing"], "Processing downstream from bioreactor"),
    ("placebocontrol", "/pləˈsiːboʊ kənˌtroʊl/", "n", "nhóm đối chứng dùng giả dược trong thử nghiệm lâm sàng", "a study design where a separate group receives an inactive dummy treatment to measure true drug efficacy", "The double-blind placebocontrol design demonstrated a statistically significant forty percent reduction in migraine frequency.", "Thiết kế nghiên cứu mù đôi có đối chứng giả dược đã chứng minh mức giảm 40% có ý nghĩa thống kê về tần suất đau nửa đầu.", ["sham treatment group"], ["placebocontrol trial"], "Controlling against placebo effect"),
    ("toxicity-screening", "/tɒkˈsɪsəti ˌskriːnɪŋ/", "n", "sàng lọc độc tính tiền lâm sàng trên mô và động vật", "preclinical assays conducted to evaluate the potential harmful or poisonous effects of candidate drug compounds", "High-throughput toxicity-screening eliminated hepatotoxic molecules prior to initiating expensive animal trials.", "Sàng lọc độc tính hiệu năng cao đã loại bỏ các phân tử gây độc cho gan trước khi bắt đầu các thử nghiệm tốn kém trên động vật.", ["safety profiling"], ["routine toxicity-screening"], "Screening for chemical toxicities"),
    ("exosome", "/ˈɛksəsoʊm/", "n", "túi ngoại bào mang phân tử sinh học liên lạc giữa tế bào", "a membrane-bound extracellular vesicle released by cells that carries proteins, lipids, and nucleic acids to other tissues", "Tumor-derived exosomes in plasma serve as non-invasive biomarkers for early liquid biopsy cancer detection.", "Các túi ngoại bào exosome có nguồn gốc từ khối u trong huyết tương đóng vai trò là dấu ấn sinh học không xâm lấn phát hiện ung thư sớm.", ["extracellular vesicle"], ["isolate exosomes"], "Exo (outside) + soma (body)"),
    ("stem-cell", "/ˈstɛm sɛl/", "n", "tế bào gốc vạn năng có khả năng biệt hóa", "an undifferentiated cell of a multicellular organism capable of giving rise to indefinitely more cells of the same type", "Induced pluripotent stem-cells offer immense therapeutic potential for regenerating damaged myocardium after infarction.", "Các tế bào gốc vạn năng cảm ứng mang lại tiềm năng điều trị to lớn để tái tạo cơ tim bị tổn thương sau nhồi máu.", ["pluripotent cell"], ["stem-cell therapy"], "Cell at the stem of lineage"),
    ("genomic-sequencing", "/dʒɪˈnoʊmɪk ˈsiːkwənsɪŋ/", "n", "giải trình tự toàn bộ hệ gen xác định trật tự nucleotit", "the laboratory process of determining the complete DNA sequence of an organism's genome at a single time", "Next-generation genomic-sequencing unmasked the rare hereditary mutation predisposing the family to cardiomyopathy.", "Giải trình tự hệ gen thế hệ mới đã hé lộ đột biến di truyền hiếm gặp khiến gia đình có nguy cơ mắc bệnh cơ tim.", ["whole genome sequencing"], ["high-throughput genomic-sequencing"], "Sequencing entire genomic bases"),
    ("knockout-mouse", "/ˈnɒkaʊt maʊs/", "n", "chuột biến đổi gen bị loại bỏ gen cụ thể để nghiên cứu", "a genetically engineered mouse in which researchers have inactivated, or 'knocked out', an existing gene", "Comparing the knockout-mouse to wild-type littermates revealed the essential role of the gene in embryonic bone development.", "So sánh chuột bị loại bỏ gen với các cá thể chuột bình thường đã tiết lộ vai trò thiết yếu của gen trong phát triển xương phôi.", ["genetically modified murine model"], ["breed a knockout-mouse"], "Gene knocked out of mouse genome"),
    ("protein-folding", "/ˈproʊtiːn ˌfoʊldɪŋ/", "n", "sự cuộn gập cấu trúc không gian 3 chiều của chuỗi protein", "the physical process by which a protein chain acquires its native 3-dimensional structure needed for biological function", "Misfolded protein aggregates from aberrant protein-folding are the hallmark of Alzheimer's disease plaques.", "Các đám rối protein bị cuộn gập sai do sự cuộn gập bất thường là dấu hiệu nhận biết của các mảng bệnh Alzheimer.", ["spatial conformation"], ["correct protein-folding"], "Folding into active 3D geometry"),
    ("chaperone-protein", "/ˈʃæpəroʊn ˌproʊtiːn/", "n", "protein hộ tống hỗ trợ các protein khác cuộn gập đúng", "proteins that assist the conformational folding or unfolding and the assembly or disassembly of macromolecular structures", "Molecular chaperone-proteins prevent hydrophobic regions of nascent peptide chains from forming toxic aggregates.", "Các protein hộ tống phân tử ngăn không cho các vùng kỵ nước của chuỗi peptide mới sinh hình thành các khối vón cục độc hại.", ["folding helper protein"], ["heat shock chaperone-protein"], "Chaperone escorting folding chains"),
    ("ligand-binding", "/ˈlaɪɡənd ˌbaɪndɪŋ/", "n", "sự liên kết giữa phối tử và thụ thể đặc hiệu", "the attachment of an effector molecule to a specific binding site on a target receptor protein", "Surface plasmon resonance measured the association and dissociation kinetics of ligand-binding with high precision.", "Hiện tượng cộng hưởng plasmon bề mặt đã đo động học liên kết và phân ly của phối tử với độ chính xác cao.", ["molecular docking"], ["affinity of ligand-binding"], "Ligand binding to receptive pocket"),
    ("drug-metabolism", "/ˈdrʌɡ məˌtæbəlɪzəm/", "n", "quá trình chuyển hóa sinh học phân giải thuốc trong cơ thể", "the metabolic breakdown of drug compounds by living organisms, usually through specialized enzymatic systems in the liver", "Phase I and Phase II hepatic drug-metabolism converts lipophilic drugs into water-soluble metabolites for urinary excretion.", "Quá trình chuyển hóa thuốc tại gan qua Pha I và Pha II giúp chuyển đổi các thuốc ưa mỡ thành các chất chuyển hóa tan trong nước để bài xuất qua nước tiểu.", ["biotransformation"], ["hepatic drug-metabolism"], "Metabolic conversion of drugs"),
    ("targeted-therapy", "/ˈtɑːrɡɪtɪd ˈθɛrəpi/", "n", "liệu pháp điều trị trúng đích nhắm thẳng vào tế bào bệnh", "cancer treatment that targets specific genes, proteins, or the tissue environment that contributes to cancer growth", "Unlike traditional cytotoxic drugs, targeted-therapy destroys malignant cells while sparing surrounding healthy tissues.", "Khác với các thuốc độc tế bào truyền thống, liệu pháp điều trị trúng đích tiêu diệt các tế bào ác tính trong khi bảo vệ các mô lành xung quanh.", ["precision oncology"], ["prescribe targeted-therapy"], "Therapy aimed at specific molecular targets"),
    ("biological-product", "/ˌbaɪəˈlɒdʒɪkl ˈprɒdʌkt/", "n", "chế phẩm sinh học sản xuất từ nguồn gốc sinh vật sống", "a wide range of products such as vaccines, blood components, somatic cells, and recombinant therapeutic proteins", "Manufacturing a biological-product requires stringent contamination controls because living cells are sensitive to shear stress.", "Việc sản xuất một chế phẩm sinh học đòi hỏi các biện pháp kiểm soát tạp nhiễm nghiêm ngặt vì tế bào sống rất nhạy cảm với ứng suất cắt.", ["biologic drug"], ["complex biological-product"], "Product derived from biological organisms"),
    ("chromatography", "/ˌkroʊməˈtɒɡrəfi/", "n", "sắc ký học phân tách hỗn hợp hóa chất phức tạp", "a laboratory technique for the separation of a mixture by passing it in solution through a medium in which components move at different rates", "High-performance liquid chromatography quantified active pharmaceutical ingredients with ninety-nine percent purity.", "Sắc ký lỏng hiệu năng cao đã định lượng các hoạt chất dược phẩm với độ tinh khiết đạt 99%.", ["separation method"], ["column chromatography"], "Chroma (color) + graphy (writing)"),
    ("crispr-editing", "/ˈkrɪspər ˌɛdɪtɪŋ/", "n", "chỉnh sửa hệ gen bằng hệ thống enzym cắt CRISPR", "the targeted modification of genetic sequences using the clustered regularly interspaced short palindromic repeats machinery", "Precise crispr-editing corrected the point mutation in hematopoietic stem cells extracted from the patient.", "Kỹ thuật chỉnh sửa gen crispr chính xác đã sửa chữa đột biến điểm trong các tế bào gốc tạo máu được chiết xuất từ bệnh nhân.", ["targeted gene editing"], ["precise crispr-editing"], "Editing genes with CRISPR cuts"),
    ("gene-therapy", "/ˈdʒiːn ˌθɛrəpi/", "n", "liệu pháp gen thay thế hoặc sửa chữa gen bệnh lý", "the introduction of normal genes into cells in place of missing or defective ones in order to correct genetic disorders", "Zolgensma is an approved gene-therapy that cures spinal muscular atrophy by delivering a functional SMN1 gene.", "Zolgensma là một liệu pháp gen đã được phê duyệt giúp chữa khỏi bệnh teo cơ tủy sống bằng cách đưa một gen SMN1 hoạt động vào cơ thể.", ["gene replacement"], ["undergo gene-therapy"], "Therapy modifying defective genes"),
    ("assay-validation", "/ˈæseɪ ˌvælɪˈdeɪʃən/", "n", "thẩm định phương pháp xét nghiệm phân tích sinh học", "the process of proving that an analytical method is acceptable for its intended purpose in terms of accuracy and precision", "Regulatory submissions require extensive assay-validation to prove the linearity and reproducibility of ELISA tests.", "Hồ sơ nộp lên cơ quan quản lý đòi hỏi việc thẩm định xét nghiệm sâu rộng để chứng minh độ tuyến tính và độ lặp lại của các xét nghiệm ELISA.", ["method qualification"], ["rigorous assay-validation"], "Validating analytical testing assays"),
    ("good-laboratory-practice", "/ɡʊd ləˈbɒrətɔːri ˈpræktɪs/", "n", "thực hành phòng thí nghiệm tốt (GLP)", "a formal quality system of management controls for research laboratories to ensure the uniformity and reliability of non-clinical safety tests", "Preclinical toxicology studies must be conducted under strict good-laboratory-practice guidelines.", "Các nghiên cứu độc tính tiền lâm sàng phải được tiến hành dưới các hướng dẫn thực hành phòng thí nghiệm tốt nghiêm ngặt.", ["GLP"], ["adhere to good-laboratory-practice"], "Good practices in laboratory management"),
    ("good-clinical-practice", "/ɡʊd ˈklɪnɪkl ˈpræktɪs/", "n", "thực hành lâm sàng tốt bảo vệ quyền lợi bệnh nhân (GCP)", "an international ethical and scientific quality standard for designing, conducting, and reporting human clinical trials", "Auditors inspect trial documentation to ensure compliance with international good-clinical-practice standards.", "Các kiểm toán viên thanh tra hồ sơ thử nghiệm để đảm bảo sự tuân thủ các tiêu chuẩn thực hành lâm sàng tốt quốc tế.", ["GCP compliance"], ["certify good-clinical-practice"], "Good practices in clinical trials"),
    ("fda-approval", "/ˌɛf diː ˈeɪ əˌpruːvl/", "n", "sự phê duyệt cấp phép lưu hành thuốc của Cục Quản lý Thực phẩm và Dược phẩm Hoa Kỳ", "official certification granted by the US Food and Drug Administration authorizing the commercial sale of a medical product", "Securing FDA-approval represents a monumental ten-year milestone for oncology biotechnology startups.", "Đạt được sự phê duyệt của FDA đại diện cho một cột mốc lịch sử 10 năm đối với các công ty khởi nghiệp công nghệ sinh học ung thư.", ["regulatory clearance"], ["grant FDA-approval", "obtain FDA-approval"], "Approval by Food and Drug Administration"),
    ("orphan-drug-designation", "/ˈɔːrfən drʌɡ ˌdɛzɪɡˈneɪʃən/", "n", "chỉ định thuốc mồ côi dành cho bệnh hiếm gặp", "a special status granted to a drug to treat a rare disease affecting a small patient population, offering market exclusivity", "The developer received orphan-drug-designation, granting seven years of market exclusivity upon commercial launch.", "Nhà phát triển đã nhận được chỉ định thuốc mồ côi, mang lại 7 năm độc quyền thị trường khi ra mắt thương mại.", ["rare disease drug status"], ["qualify for orphan-drug-designation"], "Designation for rare disease orphan drugs"),
    ("batch-release", "/ˈbætʃ rɪˌliːs/", "n", "chứng nhận giải phóng lô xuất xưởng đạt tiêu chuẩn", "the formal regulatory authorization permitting a specific production lot of pharmaceutical products to be distributed", "Quality assurance verified endotoxin and sterility testing before signing the final commercial batch-release.", "Phòng đảm bảo chất lượng đã kiểm tra nội độc tố và độ vô trùng trước khi ký giấy xuất xưởng giải phóng lô thương mại cuối cùng.", ["lot release authorization"], ["authorize batch-release"], "Releasing a validated batch to market"),
    ("fermentation", "/ˌfɜːrmənˈteɪʃən/", "n", "quá trình lên men sinh học trong nuôi cấy vi sinh vật", "the metabolic process that produces chemical changes in organic substrates through the action of enzymes and microbes", "Industrial precision fermentation produces recombinant lactoferrin identically to human breast milk proteins.", "Quá trình lên men chính xác công nghiệp sản xuất lactoferrin tái tổ hợp giống hệt protein trong sữa mẹ.", ["microbial growth reaction"], ["precision fermentation"], "Fermentare = to boil / ferment in Latin"),
    ("clinical-trial-phase", "/ˌklɪnɪkl ˈtraɪəl feɪz/", "n", "giai đoạn thử nghiệm lâm sàng (Pha I, II, III, IV)", "the distinct stages of human research testing drug safety, dosing, efficacy, and adverse effects sequentially", "Transitioning into a clinical-trial-phase 3 study requires enrolling three thousand patients across multinational medical centers.", "Chuyển sang nghiên cứu giai đoạn 3 của thử nghiệm lâm sàng đòi hỏi phải tuyển 3.000 bệnh nhân tại nhiều trung tâm y tế đa quốc gia.", ["trial development stage"], ["advance to clinical-trial-phase"], "Phases of clinical drug trials"),
    ("cell-line", "/ˈsɛl laɪn/", "n", "dòng tế bào nuôi cấy nhân tạo liên tục", "a cell culture developed from a single cell and therefore consisting of cells with a uniform genetic makeup", "The immortal HeLa cell-line has underpinned biological research into cancer, polio, and radiation for decades.", "Dòng tế bào bất tử HeLa đã làm nền tảng cho các nghiên cứu sinh học về ung thư, bại liệt và bức xạ suốt nhiều thập kỷ.", ["cultured cellular strain"], ["immortalized cell-line"], "Continuous line of dividing cells"),
    ("gene-expression", "/ˈdʒiːn ɪkˌsprɛʃən/", "n", "sự biểu hiện gen tổng hợp protein chức năng", "the process by which the information encoded in a gene is used to direct the assembly of a protein molecule", "Heat shock rapidly upregulates the gene-expression of protective chaperone proteins within five minutes.", "Sốc nhiệt làm tăng nhanh sự biểu hiện gen của các protein hộ tống bảo vệ chỉ trong vòng 5 phút.", ["protein synthesis from gene"], ["measure gene-expression"], "Expression of genetic information into traits"),
    ("enzyme-linked-immunosorbent-assay", "/ˌɛnzaɪm lɪŋkt ˌɪmjʊnoʊˈsɔːrbənt ˈæseɪ/", "n", "xét nghiệm miễn dịch hấp thụ liên kết enzym (ELISA)", "a plate-based assay technique designed for detecting and quantifying soluble substances such as peptides and antibodies", "The clinical diagnostic laboratory ran an enzyme-linked-immunosorbent-assay to screen donor blood for viral antigens.", "Phòng xét nghiệm chẩn đoán lâm sàng đã chạy xét nghiệm ELISA để sàng lọc kháng nguyên virus trong máu người hiến tặng.", ["ELISA"], ["perform enzyme-linked-immunosorbent-assay"], "Assay linking enzyme with immunosorbent"),
    ("pharmacophore", "/ˈfɑːrməkəfɔːr/", "n", "dược lực đoàn (cụm nguyên tử quyết định hoạt tính sinh học của phân tử thuốc)", "an abstract description of molecular features which are necessary for molecular recognition of a ligand by a biological macromolecule", "Medicinal chemists mapped the 3D pharmacophore to synthesize potent non-peptide agonists.", "Các nhà hóa dược đã lập bản đồ cấu trúc không gian của dược lực đoàn để tổng hợp các chất chủ vận phi peptide có hoạt lực mạnh.", ["bioactive molecular motif"], ["map the pharmacophore"], "Pharmakon (drug) + phoros (bearer)"),
    ("therapeutic-window", "/ˌθɛrəˈpjuːtɪk ˈwɪndoʊ/", "n", "khoảng điều trị an toàn và hiệu quả của thuốc", "the range of drug dosages which can treat disease effectively without having toxic effects on patients", "Maintaining cardiac glycoside serum levels within the narrow therapeutic-window prevents fatal arrhythmias.", "Duy trì nồng độ glycosid tim trong huyết thanh trong khoảng điều trị hẹp giúp ngăn ngừa rối loạn nhịp tim gây tử vong.", ["safe therapeutic dosage range"], ["narrow therapeutic-window"], "Dosage window of therapeutic efficacy"),
    ("pharmacopeia", "/ˌfɑːrməkəˈpiːə/", "n", "dược điển chính thức quy định tiêu chuẩn kiểm nghiệm thuốc quốc gia", "an official publication containing a list of medicinal drugs with their effects, directions for use, and chemical quality standards", "Generic antibiotic formulations must meet the stringent purity thresholds mandated by the United States Pharmacopeia.", "Các công thức kháng sinh gốc phải đáp ứng các ngưỡng tinh khiết nghiêm ngặt do Dược điển Hoa Kỳ quy định.", ["official drug compendium"], ["consult the pharmacopeia"], "Pharmakon (drug) + poiein (to make)"),
    ("target-engagement", "/ˈtɑːrɡɪt ɪnˌɡeɪdʒmənt/", "n", "sự gắn kết thành công của phân tử thuốc vào protein đích trong cơ thể", "the direct physical interaction between an administered drug molecule and its intended biological macromolecular target", "PET neuroimaging confirmed eighty percent receptor target-engagement in human frontal cortex tissue.", "Hình ảnh cắt lớp PET đã xác nhận 80% sự gắn kết vào thụ thể đích trong mô vỏ não trán của người.", ["binding validation"], ["demonstrate target-engagement"], "Engagement with the biological target"),
]

print(f"RAW_DATA_37 count: {len(RAW_DATA_37)}")

from data_38 import get_38
from data_39 import get_39
from data_40 import get_40

RAW_DATA_38 = get_38()
RAW_DATA_39 = get_39()
RAW_DATA_40 = get_40()

print(f"RAW_DATA_38 count: {len(RAW_DATA_38)}")
print(f"RAW_DATA_39 count: {len(RAW_DATA_39)}")
print(f"RAW_DATA_40 count: {len(RAW_DATA_40)}")

def format_cards(cards, indent=4):
    lines = []
    ind = " " * indent
    for c in cards:
        lines.append(f"{ind}{repr(c)},")
    return "\n".join(lines)

output_path = os.path.join(os.path.dirname(__file__), "data", "topup_part4_topics_37_to_40.py")

content = f'''# -*- coding: utf-8 -*-
"""
Top-up vocabulary dataset part 4 covering Topics 37-40:
37. Pharmacology, Biotechnology & Genetics
38. Corporate Law, Intellectual Property & Litigation
39. Investment Banking, Stocks & Capital Markets
40. Aviation, Flight Operations & Aerospace
"""

TOPUP_PART4 = {{
    "Pharmacology, Biotechnology & Genetics": [
{format_cards(RAW_DATA_37, 8)}
    ],
    "Corporate Law, Intellectual Property & Litigation": [
{format_cards(RAW_DATA_38, 8)}
    ],
    "Investment Banking, Stocks & Capital Markets": [
{format_cards(RAW_DATA_39, 8)}
    ],
    "Aviation, Flight Operations & Aerospace": [
{format_cards(RAW_DATA_40, 8)}
    ]
}}
'''

with open(output_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Successfully generated TOPUP_PART4 file!")
