# -*- coding: utf-8 -*-
"""
Generator for Topup Part 3: Topics 33 to 40
Fills deficits for:
33. Cloud Computing, DevOps & Microservices (50)
34. Cybersecurity, Ethical Hacking & Cryptography (50)
35. Data Science, Big Data & Analytics (50)
36. Medicine, Clinical Diagnostics & Surgery (50)
37. Pharmacology, Biotechnology & Genetics (65)
38. Corporate Law, Intellectual Property & Litigation (80)
39. Investment Banking, Stocks & Capital Markets (70)
40. Aviation, Flight Operations & Aerospace (70)
"""
import sys
if sys.stdout.encoding != 'utf-8':
    try: sys.stdout.reconfigure(encoding='utf-8')
    except Exception: pass
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
sys.path.append(str(BASE_DIR / "scripts"))
sys.path.append(str(BASE_DIR / "scripts" / "data"))

from test_combine import base_map, all_supps

def get_current_seen(topic_name):
    seen = set()
    if topic_name in base_map:
        for w in base_map[topic_name]:
            seen.add(w["word"].strip().lower())
    for t, words in all_supps.items():
        if t == topic_name:
            for w in words:
                w_val = w["word"] if isinstance(w, dict) else w[0]
                seen.add(w_val.strip().lower())
    return seen

# We construct rich pools of authentic terms for Topics 33 to 40
DATA_33_TO_40 = {
    "Cloud Computing, DevOps & Microservices": [
        ("idempotency", "/ˌaɪdəmˈpoʊtənsi/", "n", "tính lũy đẳng (thao tác lặp lại không đổi kết quả)", "the property of certain operations in mathematics and computer science whereby they can be applied multiple times without changing the result beyond the initial application", "Designing API payment webhooks with idempotency keys prevents double-charging customers.", "Thiết kế các webhook thanh toán API có tính lũy đẳng ngăn chặn việc trừ tiền khách hàng hai lần.", ["idempotent behavior"], ["idempotency key", "ensure idempotency"], "Idem (same) + potentia (power)"),
        ("orchestration", "/ˌɔːrkɪˈstreɪʃən/", "n", "sự điều phối tự động cụm dịch vụ phân tán", "the automated configuration, coordination, and management of computer systems and software", "Kubernetes provides automated container orchestration, scaling, and rolling rollouts.", "Kubernetes cung cấp khả năng điều phối, mở rộng quy mô và cập nhật luân phiên tự động cho các container.", ["automated coordination"], ["container orchestration", "workflow orchestration"], "Conducting an orchestra of containers"),
        ("canary-deployment", "/kəˈnɛəri dɪˌplɔɪmənt/", "n", "chiến lược triển khai chim hoàng yến (thử nghiệm trên tập người dùng nhỏ)", "a deployment strategy where a new version of software is exposed to a small percentage of users before broad rollout", "The team routed five percent of traffic to the canary-deployment to detect memory leaks safely.", "Nhóm đã định tuyến 5% lưu lượng truy cập sang bản triển khai thử nghiệm chim hoàng yến để phát hiện rò rỉ bộ nhớ một cách an toàn.", ["phased rollout"], ["launch canary-deployment", "monitor canary-deployment"], "Canary in a coal mine alert system"),
        ("blue-green-deployment", "/ˌbluː ˈɡriːn dɪˌplɔɪmənt/", "n", "triển khai xanh lam - xanh lục (chuyển đổi môi trường không gián đoạn)", "a release technique that uses two identical hardware environments, Blue and Green, to provide zero-downtime updates", "By switching the router from Blue to Green, the engineering team executed a zero-downtime upgrade.", "Bằng cách chuyển bộ định tuyến từ môi trường Blue sang Green, đội ngũ kỹ thuật đã nâng cấp hệ thống mà không có thời gian chết.", ["zero-downtime release"], ["execute blue-green-deployment"], "Switching between identical environments"),
        ("circuit-breaker", "/ˈsɜːrkɪt ˌbreɪkər/", "n", "bộ ngắt mạch phần mềm (ngắt kết nối dịch vụ lỗi)", "a design pattern used in software development to detect failures and encapsulate the logic of preventing a failure from constantly recurring", "The Netflix Hystrix circuit-breaker tripped when the recommendation microservice failed to respond.", "Bộ ngắt mạch Hystrix của Netflix đã được kích hoạt khi microservice đề xuất không phản hồi kịp thời.", ["fault-tolerance pattern"], ["trip the circuit-breaker", "resilient circuit-breaker"], "Electrical breaker stopping overload"),
        ("service-mesh", "/ˈsɜːrvɪs mɛʃ/", "n", "lưới dịch vụ quản lý giao tiếp nội bộ (Istio/Linkerd)", "a dedicated infrastructure layer for facilitating service-to-service communications between microservices using sidecar proxies", "Istio acts as a robust service-mesh handling mutual TLS encryption and traffic telemetry.", "Istio hoạt động như một lưới dịch vụ mạnh mẽ xử lý mã hóa TLS lẫn nhau và đo đạc lưu lượng truyền thông.", ["proxy network layer"], ["deploy a service-mesh", "service-mesh proxy"], "Mesh of sidecar network proxies"),
        ("telemetry", "/təˈlɛmɪtri/", "n", "dữ liệu đo đạc từ xa (metrics, logs, traces)", "the in situ collection of measurements or other data at remote points and their automatic transmission to receiving equipment", "Distributed telemetry enables engineers to diagnose microservice latency anomalies across continents.", "Dữ liệu đo đạc từ xa phân tán cho phép các kỹ sư chẩn đoán độ trễ bất thường của microservice trên khắp các châu lục.", ["system metrics", "observability data"], ["export telemetry", "telemetry pipeline"], "Tele (far) + metron (measure)"),
        ("tracing", "/ˈtreɪsɪŋ/", "n", "truy vết phân tán theo dõi luồng yêu cầu người dùng", "the tracking of requests through distributed systems to pinpoint bottlenecks across microservices", "OpenTelemetry distributed tracing visualized the exact database query causing latency spikes.", "Truy vết phân tán OpenTelemetry đã trực quan hóa chính xác truy vấn cơ sở dữ liệu gây ra sự cố tăng vọt độ trễ.", ["distributed tracing"], ["request tracing", "end-to-end tracing"], "Tracing request paths across servers"),
        ("sidecar-proxy", "/ˈsaɪdkɑːr ˌprɒksi/", "n", "proxy gắn kèm pod chia sẻ không gian mạng", "a design pattern where a secondary container runs alongside the main application container to handle peripheral tasks", "Envoy functions as a lightweight sidecar-proxy intercepting all inbound and outbound network traffic.", "Envoy đóng vai trò như một proxy gắn kèm gọn nhẹ đánh chặn toàn bộ lưu lượng mạng vào và ra.", ["co-located container"], ["attach sidecar-proxy", "Envoy sidecar-proxy"], "Sidecar attached to a motorcycle"),
        ("chaos-engineering", "/ˈkeɪɒs ˌɛndʒɪˈnɪərɪŋ/", "n", "kỹ nghệ hỗn loạn (cố tình gây lỗi để thử độ bền hệ thống)", "the discipline of experimenting on a software system in production to build confidence in its capability to withstand turbulence", "Netflix pioneered chaos-engineering with Chaos Monkey, randomly terminating production instances.", "Netflix đã tiên phong trong kỹ nghệ hỗn loạn với Chaos Monkey, ngẫu nhiên tắt các máy chủ chạy thực tế.", ["resilience testing"], ["practice chaos-engineering", "chaos-engineering experiment"], "Engineering order out of injected chaos"),
        ("autoscaling", "/ˈɔːtoʊˌskeɪlɪŋ/", "n", "tự động co giãn tài nguyên theo tải", "a cloud computing technique that dynamically adjusts computational resources based on real-time traffic demand", "Horizontal Pod Autoscaling increases container replicas automatically whenever CPU usage exceeds seventy percent.", "Cơ chế tự động co giãn Pod ngang sẽ tự động tăng số lượng bản sao container mỗi khi mức sử dụng CPU vượt quá 70%.", ["dynamic scaling"], ["configure autoscaling", "horizontal autoscaling"], "Scaling resources automatically"),
        ("containerization", "/kənˌteɪnəraɪˈzeɪʃən/", "n", "công nghệ đóng gói container phần mềm", "the packaging of software code with all its necessary dependencies so it can run consistently across environments", "Docker brought containerization to the mainstream software industry, replacing heavyweight virtual machines.", "Docker đã đưa công nghệ đóng gói container vào xu hướng công nghệ chính, thay thế cho các máy ảo nặng nề.", ["container packaging"], ["adopt containerization", "application containerization"], "Placing software in standardized shipping containers"),
        ("immutable-infrastructure", "/ɪˈmjuːtəbl ˌɪnfrəˈstrʌktʃər/", "n", "hạ tầng bất biến (không sửa máy chủ sống mà tạo mới)", "an infrastructure paradigm where servers are never modified after deployment, but replaced wholesale by new images", "Using immutable-infrastructure ensures that configuration drift between production servers is completely eliminated.", "Việc sử dụng hạ tầng bất biến đảm bảo rằng hiện tượng lệch cấu hình giữa các máy chủ thực tế bị loại bỏ hoàn toàn.", ["disposable infrastructure"], ["deploy immutable-infrastructure"], "Infrastructure that cannot be mutated"),
        ("configuration-drift", "/kənˌfɪɡjʊˈreɪʃən drɪft/", "n", "hiện tượng trôi dạt cấu hình máy chủ ngoài tầm kiểm soát", "the phenomenon where environment configurations diverge over time due to unrecorded manual hotfixes", "Ansible automation detects configuration-drift by comparing live server settings against declarative Git files.", "Tự động hóa Ansible phát hiện hiện tượng trôi cấu hình bằng cách so sánh cài đặt máy chủ thực tế với các tệp Git khai báo.", ["system divergence"], ["prevent configuration-drift", "detect configuration-drift"], "Drifting away from baseline config"),
        ("observability", "/əbˌzɜːrvəˈbɪləti/", "n", "khả năng quan sát toàn diện hệ thống", "the extent to which the internal states of a system can be inferred solely from its external outputs like logs, metrics, and traces", "Observability platforms like Datadog aggregate distributed telemetry to resolve outages rapidly.", "Các nền tảng quan sát toàn diện như Datadog tổng hợp dữ liệu đo đạc phân tán để xử lý sự cố gián đoạn nhanh chóng.", ["system transparency"], ["high observability", "observability pillar"], "Inferring internal state by observing outputs"),
        ("load-balancing", "/ˈloʊd ˌbælənsɪŋ/", "n", "cân bằng tải phân phối lưu lượng truy cập", "the efficient distribution of incoming network traffic across a group of backend servers", "Application load-balancing uses round-robin algorithms to prevent individual web nodes from saturating.", "Cân bằng tải ứng dụng sử dụng thuật toán round-robin để ngăn các nút máy chủ web đơn lẻ bị quá tải.", ["traffic distribution"], ["implement load-balancing", "elastic load-balancing"], "Balancing heavy workloads across nodes"),
        ("reverse-proxy", "/rɪˈvɜːrs ˌprɒksi/", "n", "máy chủ proxy ngược bảo vệ và định tuyến", "an intermediate server that intercepts requests from external clients and directs them to internal backend servers", "NGINX acts as a blazing-fast reverse-proxy providing SSL termination and gzip response compression.", "NGINX đóng vai trò như một máy chủ proxy ngược siêu tốc cung cấp khả năng xử lý giải mã SSL và nén phản hồi gzip.", ["gateway proxy"], ["configure a reverse-proxy", "reverse-proxy routing"], "Proxying on behalf of internal servers"),
        ("rate-limiting", "/ˈreɪt ˌlɪmɪtɪŋ/", "n", "giới hạn tần suất gọi API chống lạm dụng", "a strategy used by APIs to control the rate of requests that a client can make in a given timeframe", "The API gateway enforces strict rate-limiting of one hundred requests per minute per IP address.", "Cổng API áp dụng quy định giới hạn tần suất nghiêm ngặt 100 yêu cầu mỗi phút cho mỗi địa chỉ IP.", ["throttling", "traffic shaping"], ["apply rate-limiting", "rate-limiting algorithm"], "Limiting the rate of inbound traffic"),
        ("stateless-service", "/ˈsteɪtləs ˌsɜːrvɪs/", "n", "dịch vụ phi trạng thái dễ dàng mở rộng", "a software component that does not persist client session data between individual requests", "Building our checkout as a stateless-service allowed effortless horizontal scaling during Black Friday surges.", "Xây dựng hệ thống thanh toán như một dịch vụ phi trạng thái cho phép mở rộng quy mô ngang dễ dàng trong đợt giảm giá Black Friday.", ["session-free service"], ["architect a stateless-service"], "Service with no state saved between calls"),
        ("stateful-set", "/ˈsteɪtfʊl sɛt/", "n", "tập quản lý ứng dụng có trạng thái trong Kubernetes", "a Kubernetes workload API object used to manage stateful applications like distributed databases", "Deploying the PostgreSQL cluster as a StatefulSet guarantees persistent network identities and storage volumes.", "Triển khai cụm cơ sở dữ liệu PostgreSQL dưới dạng StatefulSet đảm bảo định danh mạng và khối lưu trữ bền vững.", ["stateful workload"], ["Kubernetes StatefulSet"], "Set of stateful database nodes"),
        ("dead-letter-queue", "/ˌdɛd ˈlɛtər kjuː/", "n", "hàng đợi thư chết (chứa tin nhắn xử lý lỗi)", "a service implementation within message brokers to store messages that cannot be processed successfully", "Failed payment messages were automatically routed to a dead-letter-queue for manual engineering inspection.", "Các thông điệp thanh toán bị lỗi được tự động chuyển đến hàng đợi thư chết để các kỹ sư kiểm tra thủ công.", ["DLQ", "error message queue"], ["inspect dead-letter-queue", "retry from dead-letter-queue"], "Queue for undeliverable letters"),
        ("event-sourcing", "/ɪˈvɛnt ˌsɔːrsɪŋ/", "n", "mô hình lưu trữ sự kiện thay vì trạng thái hiện tại", "an architectural pattern where state changes are logged as an immutable chronological sequence of events", "Financial accounting engines use event-sourcing to maintain an immutable historical audit trail of balance modifications.", "Các cỗ máy kế toán tài chính sử dụng mô hình lưu trữ sự kiện để duy trì dấu vết kiểm toán lịch sử bất biến về các thay đổi số dư.", ["event-driven persistence"], ["implement event-sourcing", "event-sourcing architecture"], "Deriving current state from past events"),
        ("cqrs", "/ˌsiː kjuː ɑːr ˈɛs/", "n", "tách biệt trách nhiệm truy vấn và lệnh ghi", "Command Query Responsibility Segregation, a pattern separating read and update operations for a data store", "Adopting CQRS allowed our team to optimize search queries using Elasticsearch while writing commands to PostgreSQL.", "Áp dụng mẫu hình CQRS cho phép đội ngũ tối ưu hóa truy vấn tìm kiếm bằng Elasticsearch trong khi ghi lệnh vào PostgreSQL.", ["command-query separation"], ["apply CQRS pattern"], "Command Query Responsibility Segregation"),
        ("infrastructure-as-code", "/ˌɪnfrəstrʌktʃər æz ˈkoʊd/", "n", "hạ tầng dưới dạng mã nguồn (Terraform/CloudFormation)", "the managing and provisioning of computer data centers through machine-readable definition files", "Writing infrastructure-as-code in Terraform ensures reproducible environments across development, staging, and production.", "Viết hạ tầng dưới dạng mã nguồn bằng Terraform đảm bảo khả năng tái lập môi trường đồng nhất giữa dev, staging và prod.", ["IaC"], ["adopt infrastructure-as-code", "manage infrastructure-as-code"], "Coding the infrastructure like software"),
        ("continuous-integration", "/kənˌtɪnjuəs ˌɪntɪˈɡreɪʃən/", "n", "tích hợp liên tục (tự động build và test khi merge)", "the practice of merging all developers' working copies to a shared mainline several times a day with automated builds", "The team configured GitHub Actions for continuous-integration to run three thousand unit tests on every pull request.", "Nhóm đã định cấu hình GitHub Actions để tích hợp liên tục nhằm chạy 3.000 bài kiểm thử đơn vị cho mỗi pull request.", ["CI"], ["CI pipeline", "automated continuous-integration"], "Integrating code changes continuously"),
        ("container-registry", "/kənˈteɪnər ˌrɛdʒɪstri/", "n", "kho lưu trữ hình ảnh container (Docker Hub/ECR)", "a centralized repository used for storing and distributing container images across cloud clusters", "The CI pipeline automatically pushes signed production images to the Amazon Elastic Container Registry.", "Quy trình CI tự động đẩy các hình ảnh container đã được ký xác thực lên kho lưu trữ hình ảnh của Amazon ECR.", ["image registry"], ["push to container-registry", "private container-registry"], "Registry of container images"),
        ("rolling-update", "/ˈroʊlɪŋ ˌʌpdeɪt/", "n", "cập nhật luân phiên từng máy chủ không sập hệ thống", "a deployment process that slowly replaces previous versions of an application with new instances incrementally", "Kubernetes executed a rolling-update, swapping two pods at a time without dropping client connections.", "Kubernetes đã thực hiện một đợt cập nhật luân phiên, hoán đổi hai pod một lần mà không làm gián đoạn kết nối của máy khách.", ["incremental rollout"], ["trigger rolling-update", "zero-downtime rolling-update"], "Rolling forward update pod by pod"),
        ("blue-green", "/ˌbluː ˈɡriːn/", "adj", "thuộc kỹ thuật triển khai chuyển đổi môi trường song song", "relating to the practice of maintaining two identical production environments for instant cutover", "The blue-green switch took two seconds, eliminating the thirty-minute downtime window of previous releases.", "Thao tác chuyển đổi môi trường blue-green chỉ mất hai giây, loại bỏ hoàn toàn khoảng thời gian chết 30 phút của các bản phát hành trước.", ["parallel staging cutover"], ["blue-green switch", "blue-green methodology"], "Two identical environments: blue and green"),
        ("dark-launch", "/ˈdɑːrk lɔːntʃ/", "n", "phát hành ngầm tính năng ra thực tế không báo người dùng", "releasing a feature to production but keeping it hidden or running in the background to test performance", "The engineering group conducted a dark-launch of the recommendation algorithm to measure backend database load.", "Nhóm kỹ thuật đã tiến hành phát hành ngầm thuật toán đề xuất để đo tải của cơ sở dữ liệu phía máy chủ.", ["stealth release"], ["perform a dark-launch"], "Launching in the dark without announcement"),
        ("feature-flag", "/ˈfiːtʃər flæɡ/", "n", "cờ bật tắt tính năng linh hoạt trong mã nguồn", "a software development technique that allows features to be toggled on or off remotely without redeploying code", "Using feature-flags enabled product managers to enable the new checkout UI for ten percent of UK users.", "Sử dụng cờ bật tắt tính năng cho phép các quản lý sản phẩm kích hoạt giao diện thanh toán mới cho 10% người dùng tại Anh.", ["feature toggle"], ["toggle a feature-flag", "feature-flag management"], "Flag toggling code branches"),
        ("distributed-caching", "/dɪˈstrɪbjuːtɪd ˈkæʃɪŋ/", "n", "bộ nhớ đệm phân tán tốc độ cao (Redis/Memcached)", "a cache that is distributed among multiple servers to store frequently accessed in-memory data", "A Redis cluster provides distributed-caching, slicing API response latencies from two hundred milliseconds to five.", "Cụm Redis cung cấp bộ nhớ đệm phân tán, cắt giảm độ trễ phản hồi API từ 200 mili giây xuống chỉ còn 5 mili giây.", ["in-memory caching"], ["implement distributed-caching"], "Caching across multiple memory nodes"),
        ("synthetic-monitoring", "/sɪnˈθɛtɪk ˈmɒnɪtərɪŋ/", "n", "giám sát giả lập kịch bản người dùng liên tục", "a technique that uses scripted browser sessions to simulate user paths and measure application performance", "Synthetic-monitoring alerted on-call engineers when checkout button clicks failed in the Tokyo region.", "Hệ thống giám sát giả lập đã cảnh báo các kỹ sư trực chiến khi các lượt nhấp nút thanh toán bị lỗi tại khu vực Tokyo.", ["proactive monitoring"], ["synthetic-monitoring alerts"], "Synthesized robot browser tests"),
        ("slo", "/ˌɛs ɛl ˈoʊ/", "n", "mục tiêu mức độ dịch vụ cam kết nội bộ", "Service Level Objective, a targeted level of service quality agreed upon internally within engineering teams", "Our reliability team established a ninety-nine point nine percent uptime SLO for the core payments microservice.", "Đội ngũ đảm bảo độ tin cậy đã thiết lập mục tiêu mức độ dịch vụ 99,9% thời gian hoạt động cho microservice thanh toán.", ["target reliability"], ["meet the SLO", "define an SLO"], "Service Level Objective"),
        ("sla", "/ˌɛs ɛl ˈeɪ/", "n", "thỏa thuận mức độ dịch vụ có tính pháp lý bồi thường", "Service Level Agreement, a formal contract with external customers defining service commitments and penalty clauses", "Violating the contractual 99.99% cloud SLA triggered mandatory financial credits for affected enterprise clients.", "Việc vi phạm thỏa thuận mức độ dịch vụ 99,99% trong hợp đồng đã kích hoạt các khoản bồi hoàn tài chính bắt buộc cho khách hàng.", ["legal service contract"], ["breach an SLA", "contractual SLA"], "Service Level Agreement"),
        ("sli", "/ˌɛs ɛl ˈaɪ/", "n", "chỉ số đo lường mức độ dịch vụ thực tế", "Service Level Indicator, a quantifiable metric used to measure compliance with a service level objective", "Request error rate and ninety-fifth percentile response latency are crucial SLIs for measuring API health.", "Tỷ lệ lỗi yêu cầu và độ trễ phản hồi phân vị thứ 95 là các chỉ số đo lường mức dịch vụ quan trọng để đánh giá tình trạng API.", ["reliability metric"], ["monitor SLIs", "primary SLI"], "Service Level Indicator"),
        ("error-budget", "/ˈɛrər ˌbʌdʒɪt/", "n", "ngân sách lỗi chấp nhận được trước khi đóng băng tính năng", "the maximum acceptable amount of downtime or errors that a service can accumulate before feature development is paused", "Depleting our quarterly error-budget forced the squad to prioritize infrastructure hardening over new features.", "Việc cạn kiệt ngân sách lỗi của quý đã buộc nhóm phải ưu tiên gia cố hạ tầng thay vì phát triển tính năng mới.", ["allowable downtime allowance"], ["consume error-budget", "deplete the error-budget"], "Budget for failures before freezing releases"),
        ("postmortem", "/ˌpoʊstˈmɔːrtəm/", "n", "biên bản rút kinh nghiệm sau sự cố sập hệ thống", "an analysis conducted after an incident to understand root causes and document preventive actions without assigning blame", "Following the global outage, engineering held a blameless postmortem to improve failover automation.", "Sau sự cố gián đoạn dịch vụ toàn cầu, đội ngũ kỹ thuật đã tổ chức một buổi rút kinh nghiệm không đổ lỗi để cải thiện tự động hóa dự phòng.", ["incident retrospective"], ["conduct a blameless postmortem"], "Post (after) + mortem (death of system)"),
        ("failover", "/ˈfeɪloʊvər/", "n", "cơ chế tự động chuyển đổi sang máy chủ dự phòng", "a backup operational mode in which the functions of a system are assumed by secondary components upon primary failure", "Database failover switched reads and writes to the standby replica within ten seconds of node termination.", "Cơ chế chuyển đổi dự phòng của cơ sở dữ liệu đã chuyển quyền đọc ghi sang bản sao dự phòng chỉ trong vòng 10 giây sau khi nút chính bị tắt.", ["automatic redundancy switch"], ["trigger automatic failover", "graceful failover"], "Failing over to backup server"),
        ("high-availability", "/ˌhaɪ əˌveɪləˈbɪləti/", "n", "tính sẵn sàng cao chống chịu thảm họa phần cứng", "a characteristic of a system which aims to ensure an agreed level of operational performance for a higher than normal period", "Designing for high-availability involves deploying redundant instances across at least three cloud availability zones.", "Thiết kế hệ thống có tính sẵn sàng cao đòi hỏi việc triển khai các máy chủ dự phòng trên ít nhất ba vùng khả dụng đám mây.", ["HA", "system resilience"], ["achieve high-availability", "high-availability cluster"], "Always available high uptime"),
        ("disaster-recovery", "/dɪˈzæstər rɪˌkʌvəri/", "n", "kế hoạch khắc phục sự cố sau thảm họa", "a documented set of procedures and policies to recover and protect a business IT infrastructure in the event of a disaster", "The financial corporation conducts annual disaster-recovery drills simulating total regional data center loss.", "Tập đoàn tài chính tổ chức các cuộc diễn tập khắc phục sự cố sau thảm họa hàng năm mô phỏng việc mất toàn bộ trung tâm dữ liệu khu vực.", ["DR plan"], ["disaster-recovery strategy", "disaster-recovery site"], "Recovering from catastrophic failure"),
        ("hot-standby", "/ˌhɒt ˈstændbaɪ/", "n", "máy chủ dự phòng nóng sẵn sàng đồng bộ tức thì", "a redundant backup system that runs simultaneously alongside the primary system, ready to take over immediately", "The core trading engine operates a hot-standby server synchronized with sub-millisecond replication.", "Cỗ máy giao dịch cốt lõi vận hành một máy chủ dự phòng nóng được đồng bộ hóa với độ trễ dưới một mili giây.", ["active backup node"], ["maintain a hot-standby"], "Running hot and ready to take over"),
        ("cold-standby", "/ˌkoʊld ˈstændbaɪ/", "n", "máy chủ dự phòng nguội chỉ khởi động khi cần", "a redundant backup system that is powered off or not actively processing data until the primary fails", "Using a cold-standby reduces cloud infrastructure costs but introduces a twenty-minute recovery delay.", "Sử dụng máy chủ dự phòng nguội giúp giảm chi phí hạ tầng đám mây nhưng lại tạo ra độ trễ khôi phục khoảng 20 phút.", ["passive backup"], ["switch to cold-standby"], "Cold machine needing boot up"),
        ("ingress-controller", "/ˈɪnɡrɛs kənˌtroʊlər/", "n", "bộ điều khiển cổng vào định tuyến cụm Kubernetes", "a specialized load balancer for Kubernetes environments that manages external HTTP/HTTPS access to services", "The NGINX ingress-controller handles SSL termination and URL path rewrites across sixty internal pods.", "Bộ điều khiển cổng vào NGINX xử lý việc giải mã SSL và viết lại đường dẫn URL cho 60 pod nội bộ.", ["Kubernetes gateway"], ["configure ingress-controller"], "Controlling ingress inbound traffic"),
        ("egress-traffic", "/ˈiːɡrɛs ˌtræfɪk/", "n", "lưu lượng mạng đi ra ngoài từ hệ thống đám mây", "network traffic that originates inside a private cloud network and proceeds outward to the public internet", "Companies monitor egress-traffic rigorously to prevent data exfiltration and control cloud transit bills.", "Các công ty giám sát chặt chẽ lưu lượng mạng đi ra ngoài để ngăn chặn rò rỉ dữ liệu và kiểm soát hóa đơn truyền tải đám mây.", ["outbound traffic"], ["monitor egress-traffic", "egress-traffic cost"], "Egress: moving out of boundary"),
        ("statelessness", "/ˈsteɪtləsnɪs/", "n", "tính chất phi trạng thái của kiến trúc mạng", "the quality of a computing architecture where each transaction is treated as independent with no past history stored", "Statelessness is a cornerstone architectural principle enabling horizontal auto-scaling in cloud applications.", "Tính chất phi trạng thái là nguyên tắc kiến trúc nền tảng cho phép mở rộng quy mô tự động theo chiều ngang trong các ứng dụng đám mây.", ["session independence"], ["architectural statelessness"], "State-free operational model"),
        ("ephemeral-storage", "/ɪˈfɛmərəl ˌstɔːrɪdʒ/", "n", "bộ nhớ lưu trữ tạm thời mất dữ liệu khi tắt pod", "temporary storage resources allocated to a computing instance that are discarded once the instance terminates", "Pod logs should be shipped to centralized collectors because local ephemeral-storage is wiped on container restart.", "Nhật ký của pod nên được chuyển đến các bộ thu thập tập trung vì bộ nhớ lưu trữ tạm thời cục bộ sẽ bị xóa sạch khi container khởi động lại.", ["volatile scratch disk"], ["rely on ephemeral-storage"], "Ephemeral: lasting only a short time"),
        ("persistent-volume", "/pərˌsɪstənt ˈvɒljuːm/", "n", "ổ đĩa lưu trữ dữ liệu bền vững trong cụm", "a piece of storage in a Kubernetes cluster that has a lifecycle independent of any individual pod", "The database pod claims a dedicated SSD persistent-volume to ensure customer data survives pod restarts.", "Pod cơ sở dữ liệu yêu cầu một ổ đĩa lưu trữ bền vững SSD chuyên dụng để đảm bảo dữ liệu khách hàng còn nguyên vẹn sau khi pod khởi động lại.", ["PV", "durable storage"], ["attach persistent-volume"], "Volume persisting across lifecycles"),
        ("daemonset", "/ˈdiːmən sɛt/", "n", "tập tiến trình nền chạy trên mọi nút máy chủ Kubernetes", "a Kubernetes workload that ensures that all (or some) nodes run a copy of a background pod", "We deployed Fluentbit as a DaemonSet to ensure log collection agents run on every host node in the cluster.", "Chúng tôi đã triển khai Fluentbit dưới dạng DaemonSet để đảm bảo các tiến trình thu thập nhật ký chạy trên mọi nút máy chủ trong cụm.", ["node-wide daemon workload"], ["configure a DaemonSet"], "Daemon running on all nodes set"),
        ("horizontal-pod-autoscaler", "/ˌhɒrɪˈzɒntl pɒd ˈɔːtoʊˌskeɪlər/", "n", "bộ tự động tăng giảm số lượng pod theo chiều ngang", "a Kubernetes controller that automatically scales the number of pods in a replication controller based on observed CPU utilization", "The Horizontal-Pod-Autoscaler scaled the payment gateway pods from five to forty during the holiday sale flash.", "Bộ tự động tăng giảm số lượng pod theo chiều ngang đã tăng số lượng pod cổng thanh toán từ 5 lên 40 trong đợt giảm giá chớp nhoáng dịp lễ.", ["HPA"], ["configure Horizontal-Pod-Autoscaler"], "Autoscaling pods horizontally"),
        ("vertical-pod-autoscaler", "/ˈvɜːrtɪkl pɒd ˈɔːtoʊˌskeɪlər/", "n", "bộ tự động điều chỉnh CPU/RAM cho từng pod", "a tool that automatically adjusts the CPU and memory reservations for pods to maximize resource utilization", "Using the Vertical-Pod-Autoscaler prevented our data crunching workers from suffering out-of-memory crashes.", "Sử dụng bộ tự động điều chỉnh tài nguyên pod theo chiều dọc đã giúp các tiến trình xử lý dữ liệu tránh khỏi sự cố sập do cạn kiệt bộ nhớ.", ["VPA"], ["deploy Vertical-Pod-Autoscaler"], "Autoscaling CPU and RAM vertically"),
    ],
    # Topics 34..40 will be added systematically
}

print(f"Data 33 prepared with {len(DATA_33_TO_40['Cloud Computing, DevOps & Microservices'])} terms.")
